package net.lghast.elemenix.utils;

import net.minecraft.world.item.ItemStack;

import java.util.HashMap;
import java.util.Map;

public class ElemenixMapping {
   protected static final Map<String, Constituents> ELEMENIX_MAP = new HashMap<>(Map.ofEntries(
           Map.entry("elemenix:organix_essence", new Constituents(Elemenix.ORGANIX, 486)),
           Map.entry("elemenix:terrix_essence", new Constituents(Elemenix.TERRIX, 486)),
           Map.entry("elemenix:flumix_essence", new Constituents(Elemenix.FLUMIX, 486)),
           Map.entry("elemenix:metallix_essence", new Constituents(Elemenix.METALLIX, 486)),
           Map.entry("elemenix:energix_essence", new Constituents(Elemenix.ENERGIX, 486)),
           Map.entry("elemenix:arcanix_essence", new Constituents(Elemenix.ARCANIX, 486)),

           //土与沙
           Map.entry("minecraft:dirt", new Constituents(6, 18, 0, 0, 0, 0)),
           Map.entry("minecraft:farmland", new Constituents(6, 18, 0, 0, 0, 0)),
           Map.entry("minecraft:dirt_path", new Constituents(6, 18, 0, 0, 0, 0)),
           Map.entry("minecraft:grass_block", new Constituents(10, 18, 2, 0, 0, 0)),
           Map.entry("minecraft:podzol", new Constituents(12, 16, 2, 0, 0, 0)),
           Map.entry("minecraft:mycelium", new Constituents(12, 16, 2, 0, 0, 0)),
           Map.entry("minecraft:rooted_dirt", new Constituents(12, 16, 2, 0, 0, 0)),
           Map.entry("minecraft:mud", new Constituents(6, 18, 6, 0, 0, 0)),
           Map.entry("minecraft:soul_sand", new Constituents(0, 18, 6, 0, 0, 0)),
           Map.entry("minecraft:soul_soil", new Constituents(0, 18, 6, 0, 0, 0)),
           Map.entry("#minecraft:sand", new Constituents(Elemenix.TERRIX, 8)),
           Map.entry("minecraft:glass", new Constituents(Elemenix.TERRIX, 8)),
           Map.entry("minecraft:flint", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:gravel", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:suspicious_gravel", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:clay_ball", new Constituents(Elemenix.TERRIX, 6)),
           Map.entry("minecraft:clay", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:brick", new Constituents(Elemenix.TERRIX, 6)),
           Map.entry("minecraft:bricks", new Constituents(Elemenix.TERRIX, 24)),

           //岩石与冰雪
           Map.entry("minecraft:stone", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("#minecraft:stone_tool_materials", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:diorite", new Constituents(Elemenix.TERRIX, 32)),
           Map.entry("minecraft:granite", new Constituents(Elemenix.TERRIX, 40)),
           Map.entry("minecraft:andesite", new Constituents(Elemenix.TERRIX, 28)),
           Map.entry("minecraft:deepslate", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:dripstone_block", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:pointed_dripstone", new Constituents(Elemenix.TERRIX, 6)),
           Map.entry("minecraft:tuff", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:calcite", new Constituents(Elemenix.TERRIX, 32)),
           Map.entry("minecraft:obsidian", new Constituents(Elemenix.TERRIX, 120)),
           Map.entry("minecraft:crying_obsidian", new Constituents(0, 100, 5, 0, 0, 32)),
           Map.entry("minecraft:netherrack", new Constituents(0, 19, 0, 0, 1, 0)),
           Map.entry("minecraft:crimson_nylium", new Constituents(4, 19, 0, 0, 1, 0)),
           Map.entry("minecraft:warped_nylium", new Constituents(4, 19, 0, 0, 1, 0)),
           Map.entry("minecraft:basalt", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("minecraft:gilded_blackstone", new Constituents(0, 24, 0, 48, 0, 0)),
           Map.entry("minecraft:glowstone_dust", new Constituents(0, 14, 0, 0, 10, 0)),
           Map.entry("minecraft:glowstone", new Constituents(0, 56, 0, 0, 40, 0)),
           Map.entry("minecraft:end_stone", new Constituents(Elemenix.TERRIX, 40)),
           Map.entry("minecraft:terracotta", new Constituents(Elemenix.TERRIX, 24)),
           Map.entry("#elemenix:concrete", new Constituents(2, 16, 0, 0, 0,0)),
           Map.entry("#elemenix:concrete_powder", new Constituents(2, 16, 0, 0, 0,0)),
           Map.entry("minecraft:ice", new Constituents(Elemenix.FLUMIX, 36)),
           Map.entry("minecraft:packed_ice", new Constituents(Elemenix.FLUMIX, 36)),
           Map.entry("minecraft:blue_ice", new Constituents(Elemenix.FLUMIX, 42)),
           Map.entry("minecraft:snow_block", new Constituents(Elemenix.FLUMIX, 32)),
           Map.entry("minecraft:snowball", new Constituents(Elemenix.FLUMIX, 8)),

           //矿物
           Map.entry("minecraft:charcoal", new Constituents(82, 14, 0, 0, 48, 0)),
           Map.entry("minecraft:coal", new Constituents(58, 38, 0, 0, 48, 0)),
           Map.entry("#minecraft:coal_ores", new Constituents(58, 62, 0, 0, 48, 0)),
           Map.entry("minecraft:iron_ingot", new Constituents(0, 9, 0, 216, 0, 0)),
           Map.entry("minecraft:iron_nugget", new Constituents(0, 1, 0, 24, 0, 0)),
           Map.entry("minecraft:raw_iron", new Constituents(Elemenix.TERRIX, 225)),
           Map.entry("#minecraft:iron_ores", new Constituents(Elemenix.TERRIX, 249)),
           Map.entry("minecraft:copper_ingot", new Constituents(0, 24, 0, 72, 0, 0)),
           Map.entry("minecraft:raw_copper", new Constituents(Elemenix.TERRIX, 96)),
           Map.entry("#minecraft:copper_ores", new Constituents(Elemenix.TERRIX, 120)),
           Map.entry("minecraft:gold_ingot", new Constituents(Elemenix.METALLIX, 432)),
           Map.entry("minecraft:gold_nugget", new Constituents(Elemenix.METALLIX, 48)),
           Map.entry("minecraft:raw_gold", new Constituents(Elemenix.METALLIX, 432)),
           Map.entry("#minecraft:gold_ores", new Constituents(0, 24, 0, 432, 0, 0)),
           Map.entry("minecraft:nether_gold_ore", new Constituents(0, 19, 0, 432, 1, 0)),
           Map.entry("minecraft:diamond", new Constituents(0, 20000, 0, 0, 0, 400)),
           Map.entry("#minecraft:diamond_ores", new Constituents(0, 20024, 0, 0, 0, 400)),
           Map.entry("minecraft:netherite_scrap", new Constituents(0, 8000, 0, 12000, 0, 900)),
           Map.entry("minecraft:ancient_debris", new Constituents(0, 7500, 0, 12100, 0, 900)),
           Map.entry("minecraft:netherite_ingot", new Constituents(0, 30000, 0, 49728, 0, 3600)),
           Map.entry("minecraft:redstone", new Constituents(0, 18, 0, 0, 6, 0)),
           Map.entry("#minecraft:redstone_ores", new Constituents(0, 42, 0, 0, 6, 0)),
           Map.entry("minecraft:lapis_lazuli", new Constituents(Elemenix.TERRIX, 18)),
           Map.entry("#minecraft:lapis_ores", new Constituents(Elemenix.TERRIX, 42)),
           Map.entry("minecraft:emerald", new Constituents(Elemenix.TERRIX, 800)),
           Map.entry("#minecraft:emerald_ores", new Constituents(Elemenix.TERRIX, 824)),
           Map.entry("minecraft:amethyst_shard", new Constituents(Elemenix.TERRIX, 300)),
           Map.entry("minecraft:amethyst_cluster", new Constituents(Elemenix.TERRIX, 1200)),
           Map.entry("minecraft:small_amethyst_bud", new Constituents(Elemenix.TERRIX, 300)),
           Map.entry("minecraft:medium_amethyst_bud", new Constituents(Elemenix.TERRIX, 600)),
           Map.entry("minecraft:large_amethyst_bud", new Constituents(Elemenix.TERRIX, 900)),
           Map.entry("minecraft:quartz", new Constituents(Elemenix.TERRIX, 8)),
           Map.entry("minecraft:nether_quartz_ore", new Constituents(0, 27, 0, 0, 1, 0)),
           Map.entry("minecraft:exposed_copper", new Constituents(0, 346, 0, 518, 0, 0)),
           Map.entry("minecraft:weathered_copper", new Constituents(0, 540, 0, 324, 0, 0)),
           Map.entry("minecraft:oxidized_copper", new Constituents(0, 734, 0, 130, 0, 0)),

           //植物
           Map.entry("#minecraft:planks", new Constituents(Elemenix.ORGANIX, 24)),
           Map.entry("#minecraft:logs", new Constituents(Elemenix.ORGANIX, 96)),
           Map.entry("minecraft:stick", new Constituents(Elemenix.ORGANIX, 12)),
           Map.entry("minecraft:bamboo", new Constituents(Elemenix.ORGANIX, 6)),
           Map.entry("minecraft:stripped_bamboo_block", new Constituents(Elemenix.ORGANIX, 54)),
           Map.entry("minecraft:mangrove_roots", new Constituents(Elemenix.ORGANIX, 18)),
           Map.entry("minecraft:hanging_roots", new Constituents(Elemenix.ORGANIX, 6)),
           Map.entry("#minecraft:saplings", new Constituents(64, 0, 24, 0, 0, 0)),
           Map.entry("minecraft:carrot", new Constituents(20, 0, 12, 0, 0, 0)),
           Map.entry("minecraft:potato", new Constituents(24, 0, 8, 0, 0, 0)),
           Map.entry("minecraft:poisonous_potato", new Constituents(24, 0, 8, 0, 0, 0)),
           Map.entry("minecraft:beetroot", new Constituents(20, 0, 12, 0, 0, 0)),
           Map.entry("minecraft:wheat", new Constituents(Elemenix.ORGANIX, 24)),
           Map.entry("minecraft:pumpkin", new Constituents(72, 0, 68, 0, 0, 0)),
           Map.entry("minecraft:carved_pumpkin", new Constituents(56, 0, 68, 0, 0, 0)),
           Map.entry("minecraft:melon", new Constituents(72, 0, 108, 0, 0, 0)),
           Map.entry("minecraft:melon_slice", new Constituents(8, 0, 12, 0, 0, 0)),
           Map.entry("minecraft:sugar_cane", new Constituents(20, 0, 12, 0, 0, 0)),
           Map.entry("minecraft:apple", new Constituents(32, 0, 15, 0, 0, 0)),
           Map.entry("minecraft:enchanted_golden_apple", new Constituents(32, 0, 15, 31104, 0, 2000)),
           Map.entry("minecraft:cocoa_beans", new Constituents(18, 0, 6, 0, 0, 0)),
           Map.entry("minecraft:sweet_berries", new Constituents(8, 0, 6, 0, 0, 0)),
           Map.entry("minecraft:glow_berries", new Constituents(8, 0, 4, 0, 2, 0)),
           Map.entry("#minecraft:chicken_food", new Constituents(Elemenix.ORGANIX, 4)),
           Map.entry("minecraft:red_mushroom", new Constituents(18, 0, 6, 0, 0, 0)),
           Map.entry("minecraft:brown_mushroom", new Constituents(18, 0, 6, 0, 0, 0)),
           Map.entry("minecraft:red_mushroom_block", new Constituents(36, 0, 12, 0, 0, 0)),
           Map.entry("minecraft:brown_mushroom_block", new Constituents(36, 0, 12, 0, 0, 0)),
           Map.entry("minecraft:mushroom_stem", new Constituents(36, 0, 12, 0, 0, 0)),
           Map.entry("minecraft:crimson_fungus", new Constituents(64, 0, 24, 0, 0, 0)),
           Map.entry("minecraft:warped_fungus", new Constituents(64, 0, 24, 0, 0, 0)),
           Map.entry("#minecraft:small_flowers", new Constituents(18, 0, 8, 0, 0, 0)),
           Map.entry("#elemenix:big_flowers", new Constituents(36, 0, 16, 0, 0, 0)),
           Map.entry("minecraft:pink_petals", new Constituents(18, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:wither_rose", new Constituents(18, 0, 5, 0, 0, 5)),
           Map.entry("minecraft:spore_blossom", new Constituents(56, 0, 24, 0, 0, 0)),
           Map.entry("minecraft:short_grass", new Constituents(6, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:tall_grass", new Constituents(12, 0, 4, 0, 0, 0)),
           Map.entry("minecraft:fern", new Constituents(6, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:large_fern", new Constituents(12, 0, 4, 0, 0, 0)),
           Map.entry("#minecraft:leaves", new Constituents(6, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:lily_pad", new Constituents(18, 0, 10, 0, 0, 0)),
           Map.entry("minecraft:cactus", new Constituents(18, 0, 10, 0, 0, 0)),
           Map.entry("minecraft:glow_lichen", new Constituents(6, 0, 2, 0, 2, 0)),
           Map.entry("minecraft:dead_bush", new Constituents(Elemenix.ORGANIX, 12)),
           Map.entry("minecraft:seagrass", new Constituents(6, 0, 4, 0, 0, 0)),
           Map.entry("minecraft:kelp", new Constituents(6, 0, 4, 0, 0, 0)),
           Map.entry("minecraft:sea_pickle", new Constituents(18, 0, 12, 0, 5, 0)),
           Map.entry("minecraft:big_dripleaf", new Constituents(36, 0, 10, 0, 0, 0)),
           Map.entry("minecraft:small_dripleaf", new Constituents(18, 0, 10, 0, 0, 0)),
           Map.entry("minecraft:moss_block", new Constituents(6, 0, 6, 0, 0, 0)),
           Map.entry("minecraft:moss_carpet", new Constituents(4, 0, 4, 0, 0, 0)),
           Map.entry("minecraft:vine", new Constituents(6, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:weeping_vines", new Constituents(6, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:twisting_vines", new Constituents(6, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:nether_sprouts", new Constituents(6, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:crimson_roots", new Constituents(18, 0, 2, 0, 4, 0)),
           Map.entry("minecraft:warped_roots", new Constituents(18, 0, 2, 0, 4, 0)),
           Map.entry("minecraft:nether_wart", new Constituents(15, 0, 3, 0, 2, 1)),
           Map.entry("minecraft:nether_wart_block", new Constituents(32, 0, 10, 0, 8, 2)),
           Map.entry("minecraft:warped_wart_block", new Constituents(32, 0, 10, 0, 8, 2)),
           Map.entry("minecraft:shroomlight", new Constituents(24, 0, 5, 0, 40, 0)),
           Map.entry("minecraft:chorus_fruit", new Constituents(32, 0, 3, 0, 0, 6)),
           Map.entry("minecraft:chorus_flower", new Constituents(45, 0, 5, 0, 0, 10)),
           Map.entry("minecraft:chorus_plant", new Constituents(13, 0, 2, 0, 0, 4)),

           //动物与怪物
           Map.entry("minecraft:white_wool", new Constituents(Elemenix.ORGANIX, 96)),
           Map.entry("#elemenix:dyed_wools", new Constituents(Elemenix.ORGANIX, 114)),
           Map.entry("minecraft:leather", new Constituents(Elemenix.ORGANIX, 32)),
           Map.entry("minecraft:rabbit_hide", new Constituents(Elemenix.ORGANIX, 8)),
           Map.entry("minecraft:rabbit_foot", new Constituents(64, 12, 12, 0, 0, 10)),
           Map.entry("minecraft:feather", new Constituents(Elemenix.ORGANIX, 24)),
           Map.entry("minecraft:egg", new Constituents(6, 8, 6, 0, 0, 0)),
           Map.entry("minecraft:turtle_egg", new Constituents(32, 16, 12, 0, 0, 0)),
           Map.entry("minecraft:sniffer_egg", new Constituents(70, 32, 24, 0, 0, 0)),
           Map.entry("minecraft:ink_sac", new Constituents(24, 4, 4, 0, 0, 0)),
           Map.entry("minecraft:glow_ink_sac", new Constituents(24, 8, 4, 0, 6, 0)),
           Map.entry("minecraft:honeycomb", new Constituents(Elemenix.ORGANIX, 60)),
           Map.entry("minecraft:bee_nest", new Constituents(Elemenix.ORGANIX, 240)),
           Map.entry("minecraft:honey_bottle", new Constituents(60, 8, 0, 0, 0, 0)),
           Map.entry("minecraft:goat_horn", new Constituents(10, 80, 0, 0, 0, 2)),
           Map.entry("minecraft:turtle_scute", new Constituents(160, 0, 0, 0, 0, 20)),
           Map.entry("minecraft:armadillo_scute", new Constituents(32, 0, 0, 0, 0, 0)),
           Map.entry("#elemenix:froglights", new Constituents(32, 16, 0, 0, 12, 0)),
           Map.entry("minecraft:frogspawn", new Constituents(70, 0, 40, 0, 0, 0)),
           Map.entry("#elemenix:corals", new Constituents(18, 8, 8, 0, 0, 0)),
           Map.entry("#elemenix:dead_corals", new Constituents(18, 8, 0, 0, 0, 0)),
           Map.entry("#elemenix:coral_blocks", new Constituents(36, 16, 16, 0, 0, 0)),
           Map.entry("#elemenix:dead_coral_blocks", new Constituents(36, 16, 0, 0, 0, 0)),
           Map.entry("minecraft:rotten_flesh", new Constituents(18, 0, 2, 0, 0, 0)),
           Map.entry("minecraft:bone", new Constituents(6, 24, 0, 0, 0, 0)),
           Map.entry("minecraft:bone_meal", new Constituents(2, 8, 0, 0, 0, 0)),
           Map.entry("minecraft:string", new Constituents(Elemenix.ORGANIX, 24)),
           Map.entry("minecraft:cobweb", new Constituents(Elemenix.ORGANIX, 36)),
           Map.entry("minecraft:spider_eye", new Constituents(32, 0, 8, 0, 0, 1)),
           Map.entry("minecraft:gunpowder", new Constituents(0, 24, 0, 0, 8, 0)),
           Map.entry("minecraft:slime_ball", new Constituents(35, 0, 10, 0, 0, 2)),
           Map.entry("minecraft:phantom_membrane", new Constituents(35, 0, 0, 0, 0, 8)),
           Map.entry("minecraft:nautilus_shell", new Constituents(0, 128, 0, 0, 0, 5)),
           Map.entry("minecraft:prismarine_crystals", new Constituents(0, 10, 0, 0, 6, 0)),
           Map.entry("minecraft:prismarine_shard", new Constituents(0, 12, 0, 0, 0, 0)),
           Map.entry("minecraft:wet_sponge", new Constituents(132, 0, 120, 0, 0, 0)),
           Map.entry("minecraft:totem_of_undying", new Constituents(0, 320, 0, 1024, 0, 100)),
           Map.entry("minecraft:blaze_rod", new Constituents(Elemenix.ENERGIX, 72)),
           Map.entry("minecraft:blaze_powder", new Constituents(Elemenix.ENERGIX, 36)),
           Map.entry("minecraft:breeze_rod", new Constituents(Elemenix.FLUMIX, 72)),
           Map.entry("minecraft:wind_charge", new Constituents(Elemenix.FLUMIX, 18)),
           Map.entry("minecraft:ghast_tear", new Constituents(24, 0, 120, 0, 0, 200)),
           Map.entry("minecraft:magma_cream", new Constituents(0, 12, 0, 0, 30, 2)),
           Map.entry("minecraft:ender_pearl", new Constituents(0, 20, 0, 0, 0, 160)),
           Map.entry("minecraft:shulker_shell", new Constituents(0, 128, 0, 0, 0, 20)),
           Map.entry("minecraft:nether_star", new Constituents(0, 512, 32, 0, 20240, 4096)),
           Map.entry("minecraft:dragon_egg", new Constituents(1280, 1024, 1280, 0, 14400, 14400)),
           Map.entry("minecraft:dragon_breath", new Constituents(0, 8, 60, 0, 10, 50)),

           //食物
           Map.entry("minecraft:chicken", new Constituents(30, 0, 8, 0, 0, 0)),
           Map.entry("minecraft:mutton", new Constituents(30, 0, 8, 0, 0, 0)),
           Map.entry("minecraft:beef", new Constituents(40, 0, 8, 0, 0, 0)),
           Map.entry("minecraft:porkchop", new Constituents(40, 0, 8, 0, 0, 0)),
           Map.entry("minecraft:rabbit", new Constituents(25, 0, 8, 0, 0, 0)),
           Map.entry("minecraft:cod", new Constituents(25, 2, 8, 0, 0, 0)),
           Map.entry("minecraft:salmon", new Constituents(30, 2, 8, 0, 0, 0)),
           Map.entry("minecraft:tropical_fish", new Constituents(20, 2, 12, 0, 0, 0)),
           Map.entry("minecraft:pufferfish", new Constituents(30, 3, 10, 0, 0, 5)),
           Map.entry("minecraft:sugar", new Constituents(Elemenix.ORGANIX, 20)),
           Map.entry("minecraft:bread", new Constituents(Elemenix.ORGANIX, 72)),
           Map.entry("minecraft:dried_kelp_block", new Constituents(54, 0, 0, 0, 54, 0)),
           Map.entry("minecraft:suspicious_stew", new Constituents(72, 0, 20, 0, 0, 0)),

           //其他
           Map.entry("minecraft:paper", new Constituents(Elemenix.ORGANIX, 20)),
           Map.entry("minecraft:book", new Constituents(Elemenix.ORGANIX, 92)),
           Map.entry("minecraft:writable_book", new Constituents(140, 4, 0, 0, 0, 0)),
           Map.entry("minecraft:written_book", new Constituents(140, 4, 0, 0, 0, 0)),
           Map.entry("#c:dyes", new Constituents(Elemenix.ORGANIX, 18)),
           Map.entry("minecraft:white_bed", new Constituents(Elemenix.ORGANIX, 360)),
           Map.entry("#elemenix:dyed_beds", new Constituents(Elemenix.ORGANIX, 414)),
           Map.entry("#elemenix:dyed_shulker_boxes", new Constituents(210, 256, 0, 0, 0, 40)),
           Map.entry("minecraft:bucket", new Constituents(0, 27, 0, 648, 0, 0)),
           Map.entry("minecraft:water_bucket", new Constituents(0, 27, 0, 648, 0, 0)),
           Map.entry("minecraft:powder_snow_bucket", new Constituents(0, 27, 32, 648, 0, 0)),
           Map.entry("minecraft:milk_bucket", new Constituents(5, 27, 6, 648, 0, 0)),
           Map.entry("minecraft:lava_bucket", new Constituents(0, 147, 0, 648, 0, 0)),
           Map.entry("minecraft:cod_bucket", new Constituents(25, 29, 8, 648, 0, 0)),
           Map.entry("minecraft:salmon_bucket", new Constituents(30, 29, 8, 648, 0, 0)),
           Map.entry("minecraft:tropical_fish_bucket", new Constituents(20, 29, 12, 648, 0, 0)),
           Map.entry("minecraft:pufferfish_bucket", new Constituents(30, 30, 10, 648, 0, 5)),
           Map.entry("minecraft:tadpole_bucket", new Constituents(20, 27, 15, 648, 0, 0)),
           Map.entry("minecraft:axolotl_bucket", new Constituents(50, 32, 25, 648, 0, 0)),
           Map.entry("minecraft:saddle", new Constituents(96, 9, 0, 216, 0, 0)),
           Map.entry("minecraft:name_tag", new Constituents(360, 0, 0, 0, 0, 80)),
           Map.entry("minecraft:chainmail_helmet", new Constituents(0, 36, 0, 864, 0, 0)),
           Map.entry("minecraft:chainmail_chestplate", new Constituents(0, 58, 0, 1382, 0, 0)),
           Map.entry("minecraft:chainmail_leggings", new Constituents(0, 50, 0, 1210, 0, 0)),
           Map.entry("minecraft:chainmail_boots", new Constituents(0, 29, 0, 691, 0, 0)),
           Map.entry("minecraft:heart_of_the_sea", new Constituents(0, 0, 10000, 0, 120, 100)),
           Map.entry("minecraft:heavy_core", new Constituents(0, 20, 0, 32000, 0, 400)),
           Map.entry("minecraft:trident", new Constituents(0, 500, 0, 25000, 0, 1020)),
           Map.entry("minecraft:netherite_upgrade_smithing_template", new Constituents(0, 140019, 0, 0, 1, 2800)),
           Map.entry("minecraft:sentry_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:dune_armor_trim_smithing_template", new Constituents(0, 140032, 0, 0, 0, 2800)),
           Map.entry("minecraft:coast_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:wild_armor_trim_smithing_template", new Constituents(6, 140024, 2, 0, 0, 2800)),
           Map.entry("minecraft:ward_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:eye_armor_trim_smithing_template", new Constituents(0, 140040, 0, 0, 0, 2800)),
           Map.entry("minecraft:vex_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:tide_armor_trim_smithing_template", new Constituents(0, 140048, 0, 0, 0, 2800)),
           Map.entry("minecraft:snout_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:rib_armor_trim_smithing_template", new Constituents(0, 140019, 0, 0, 1, 2800)),
           Map.entry("minecraft:spire_armor_trim_smithing_template", new Constituents(0, 140032, 0, 0, 0, 2806)),
           Map.entry("minecraft:wayfinder_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:shaper_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:raiser_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:host_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:silence_armor_trim_smithing_template", new Constituents(0, 140024, 0, 0, 0, 2800)),
           Map.entry("minecraft:flow_armor_trim_smithing_template", new Constituents(0, 14000, 72, 0, 0, 2800)),
           Map.entry("minecraft:bolt_armor_trim_smithing_template", new Constituents(0, 140216, 0, 648, 0, 2800)),
           Map.entry("minecraft:sculk", new Constituents(0, 0, 0, 0, 2, 4)),
           Map.entry("minecraft:sculk_vein", new Constituents(0, 0, 0, 0, 1, 1)),
           Map.entry("minecraft:sculk_catalyst", new Constituents(0, 12, 0, 0, 8, 20)),
           Map.entry("minecraft:sculk_sensor", new Constituents(12, 0, 0, 0, 10, 10)),
           Map.entry("minecraft:sculk_shrieker", new Constituents(0, 12, 32, 0, 15, 30)),
           Map.entry("minecraft:echo_shard", new Constituents(0, 5, 0, 0, 5, 8)),
           Map.entry("#minecraft:decorated_pot_sherds", new Constituents(0, 6, 0, 0, 0, 12)),
           Map.entry("minecraft:elytra", new Constituents(5250, 0, 0, 0, 0, 3200)),
           Map.entry("minecraft:netherite_helmet", new Constituents(0, 270019, 0, 49728, 1, 8400)),
           Map.entry("minecraft:netherite_chestplate", new Constituents(0, 330019, 0, 49728, 1, 9600)),
           Map.entry("minecraft:netherite_leggings", new Constituents(0, 310019, 0, 49728, 1, 9200)),
           Map.entry("minecraft:netherite_boots", new Constituents(0, 250019, 0, 49728, 1, 8000)),
           Map.entry("minecraft:netherite_pickaxe", new Constituents(24, 230019, 0, 49728, 1, 7600)),
           Map.entry("minecraft:netherite_axe", new Constituents(24, 230019, 0, 49728, 1, 7600)),
           Map.entry("minecraft:netherite_hoe", new Constituents(24, 210019, 0, 49728, 1, 7200)),
           Map.entry("minecraft:netherite_sword", new Constituents(12, 210019, 0, 49728, 1, 7200)),
           Map.entry("minecraft:netherite_shovel", new Constituents(24, 190019, 0, 49728, 1, 6800)),
           Map.entry("minecraft:chipped_anvil", new Constituents(0, 195, 0, 4687, 0, 0)),
           Map.entry("minecraft:damaged_anvil", new Constituents(0, 140, 0, 3348, 0, 0)),
           Map.entry("minecraft:bell", new Constituents(64, 0, 432, 0, 0, 0)),
           Map.entry("minecraft:skeleton_skull", new Constituents(0, 360, 0, 0, 0, 10)),
           Map.entry("minecraft:wither_skeleton_skull", new Constituents(0, 400, 0, 0, 50, 400)),
           Map.entry("minecraft:creeper_head", new Constituents(280, 80, 10, 0, 30, 500)),
           Map.entry("minecraft:zombie_head", new Constituents(280, 80, 0, 0, 0, 500)),
           Map.entry("minecraft:player_head", new Constituents(280, 80, 10, 0, 0, 500)),
           Map.entry("minecraft:piglin_head", new Constituents(300, 80, 10, 0, 0, 500)),
           Map.entry("minecraft:dragon_head", new Constituents(3200, 1000, 800, 0, 3000, 2000)),
           Map.entry("#elemenix:infested_stones", new Constituents(24, 24, 5, 0, 0, 0)),
           Map.entry("minecraft:iron_horse_armor", new Constituents(32, 54, 0, 1296, 0, 0)),
           Map.entry("minecraft:golden_horse_armor", new Constituents(32, 0, 0, 2592, 0, 0)),
           Map.entry("minecraft:diamond_horse_armor", new Constituents(32, 120000, 0, 0, 0, 24000)),
           Map.entry("minecraft:experience_bottle", new Constituents(0, 8, 0, 0, 4, 8)),
           Map.entry("minecraft:trial_key", new Constituents(0, 0, 0, 240, 0, 40)),
           Map.entry("minecraft:ominous_trial_key", new Constituents(0, 0, 0, 720, 0, 800)),
           Map.entry("#elemenix:vinyl_discs", new Constituents(550, 0, 0, 0, 0, 300)),
           Map.entry("#c:music_discs", new Constituents(550, 0, 0, 0, 0, 300)),
           Map.entry("minecraft:music_disc_pigstep", new Constituents(0, 550, 0, 0, 5, 300)),
           Map.entry("minecraft:music_disc_relic", new Constituents(0, 550, 0, 0, 0, 300)),
           Map.entry("minecraft:music_disc_creator", new Constituents(0, 550, 0, 0, 0, 300)),
           Map.entry("minecraft:music_disc_creator_music_box", new Constituents(0, 50, 500, 0, 0, 300)),
           Map.entry("minecraft:music_disc_precipice", new Constituents(225, 225, 0, 0, 0, 300)),
           Map.entry("minecraft:disc_fragment_5", new Constituents(0, 35, 35, 0, 0, 45)),
           Map.entry("minecraft:firework_rocket", new Constituents(6, 8, 0, 0, 1, 0)),
           Map.entry("minecraft:firework_star", new Constituents(18, 24, 0, 0, 8, 0)),
           Map.entry("minecraft:globe_banner_pattern", new Constituents(200, 30, 70, 0, 0, 50)),
           Map.entry("minecraft:piglin_banner_pattern", new Constituents(200, 0, 0, 0, 50, 50)),
           Map.entry("minecraft:flow_banner_pattern", new Constituents(200, 0, 120, 0, 0, 50)),
           Map.entry("minecraft:guster_banner_pattern", new Constituents(200, 0, 120, 0, 0, 50)),
           Map.entry("minecraft:air", new Constituents(true))
    ));
}
