package net.lghast.elemenix.utils;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.function.Supplier;

public class ModElemenixMapping {
    private static final Map<String, Supplier<Map<String, Constituents>>> MOD_ELEMENIX_MAPPINGS = new HashMap<>();

    static {
        registerModMappings("farmersdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("farmersdelight:straw", new Constituents(Elemenix.ORGANIX, 24));
            map.put("farmersdelight:tomato", new Constituents(20, 0, 12, 0, 0, 0));
            map.put("farmersdelight:rotten_tomato", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("farmersdelight:onion", new Constituents(20, 0, 10, 0, 0, 0));
            map.put("farmersdelight:cabbage", new Constituents(26, 0, 8, 0, 0, 0));
            map.put("farmersdelight:rice_panicle", new Constituents(24, 0, 5, 0, 0, 0));
            map.put("farmersdelight:rice", new Constituents(24, 0, 0, 0, 0, 0));
            map.put("farmersdelight:tree_bark", new Constituents(Elemenix.ORGANIX, 7));
            map.put("#farmersdelight:barks", new Constituents(Elemenix.ORGANIX, 7));
            map.put("farmersdelight:rope", new Constituents(12, 0, 0, 0, 0, 0));
            map.put("farmersdelight:sandy_shrub", Constituents.grassVineLeaves());
            map.put("farmersdelight:canvas", new Constituents(Elemenix.ORGANIX, 96));
            map.put("farmersdelight:tatami", new Constituents(Elemenix.ORGANIX, 120));
            map.put("farmersdelight:full_tatami_mat", new Constituents(Elemenix.ORGANIX, 60));
            map.put("#farmersdelight:wild_crops", new Constituents(64, 0, 24, 0, 0, 0));
            map.put("farmersdelight:brown_mushroom_colony", new Constituents(90, 0, 30, 0, 0, 0));
            map.put("farmersdelight:red_mushroom_colony", new Constituents(90, 0, 30, 0, 0, 0));
            map.put("farmersdelight:wheat_dough", new Constituents(24, 0, 4, 0, 0, 0));
            map.put("farmersdelight:chicken_cuts", new Constituents(15, 0, 4, 0, 0, 0));
            map.put("farmersdelight:cod_slice", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("farmersdelight:salmon_slice", new Constituents(15, 0, 4, 0, 0, 0));
            map.put("farmersdelight:ham", new Constituents(86, 24, 16, 0, 0, 0));
            map.put("farmersdelight:smoked_ham", new Constituents(86, 24, 3, 0, 10, 0));
            map.put("farmersdelight:cake_slice", new Constituents(17, 0, 1, 0, 0, 0));
            map.put("farmersdelight:apple_pie_slice", new Constituents(70, 0, 11, 0, 0, 0));
            map.put("farmersdelight:chocolate_pie_slice", new Constituents(42, 0, 5, 0, 0, 0));
            map.put("farmersdelight:sweet_berry_cheesecake_slice", new Constituents(30, 0, 9, 0, 0, 0));
            map.put("farmersdelight:roast_chicken", new Constituents(72, 0, 10, 0, 7, 0));
            map.put("farmersdelight:shepherds_pie", new Constituents(51, 0, 5, 0, 12, 0));
            map.put("farmersdelight:stuffed_pumpkin", new Constituents(64, 0, 27, 0, 0, 0));
            map.put("farmersdelight:honey_glazed_ham", new Constituents(74, 0, 6, 0, 2, 0));
            map.put("farmersdelight:rich_soil", new Constituents(86, 34, 0, 0, 0, 0));
            map.put("farmersdelight:rich_soil_farmland", new Constituents(86, 34, 0, 0, 0, 0));
            return map;
        });

        registerModMappings("twilightforest", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("twilightforest:chiseled_canopy_bookshelf", new Constituents(Elemenix.ORGANIX, 180));
            map.put("twilightforest:mangrove_root", new Constituents(Elemenix.ORGANIX, 18));
            map.put("twilightforest:root", new Constituents(Elemenix.ORGANIX, 18));
            map.put("twilightforest:moss_patch", new Constituents(3, 0, 2, 0, 0, 0));
            map.put("twilightforest:mining_log_core", new Constituents(96, 0, 0, 30, 0, 500));
            map.put("twilightforest:time_log_core", new Constituents(96, 0, 0, 30, 50, 450));
            map.put("twilightforest:transformation_log_core", new Constituents(96, 0, 0, 30, 50, 450));
            map.put("twilightforest:sorting_log_core", new Constituents(96, 0, 0, 30, 0, 500));
            map.put("twilightforest:mayapple", Constituents.grassVineLeaves());
            map.put("twilightforest:clover_patch", Constituents.grassVineLeaves());
            map.put("twilightforest:fiddlehead", Constituents.grassVineLeaves());
            map.put("twilightforest:mushgloom", new Constituents(18, 0, 6, 0, 2, 0));
            map.put("twilightforest:huge_mushgloom", new Constituents(36, 0, 12, 0, 4, 0));
            map.put("twilightforest:huge_mushgloom_stem", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("twilightforest:torchberries", new Constituents(8, 0, 4, 0, 2, 0));
            map.put("twilightforest:torchberry_plant", new Constituents(24, 0, 10, 0, 5, 0));
            map.put("twilightforest:fallen_leaves", new Constituents(4, 0, 2, 0, 0, 0));
            map.put("twilightforest:root_strand", new Constituents(Elemenix.ORGANIX, 12));
            map.put("twilightforest:hedge", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("twilightforest:firefly", new Constituents(18, 2, 5, 0, 3, 0));
            map.put("twilightforest:cicada", new Constituents(20, 0, 8, 0, 0, 0));
            map.put("twilightforest:moonworm", new Constituents(18, 0, 5, 0, 2, 0));
            map.put("twilightforest:moonworm_queen", new Constituents(180, 0, 60, 0, 50, 50));
            map.put("twilightforest:nagastone", Constituents.stone());
            map.put("twilightforest:etched_nagastone", Constituents.stone());
            map.put("twilightforest:nagastone_head", Constituents.stone());
            map.put("twilightforest:nagastone_pillar", Constituents.stone());
            map.put("twilightforest:nagastone_stairs_left", Constituents.stone());
            map.put("twilightforest:nagastone_stairs_right", Constituents.stone());
            map.put("twilightforest:cracked_nagastone_stairs_left", Constituents.stone());
            map.put("twilightforest:cracked_nagastone_stairs_right", Constituents.stone());
            map.put("twilightforest:mossy_nagastone_stairs_left", new Constituents(6, 24, 0, 0, 0, 0));
            map.put("twilightforest:mossy_nagastone_stairs_right", new Constituents(6, 24, 0, 0, 0, 0));
            map.put("twilightforest:mazestone", new Constituents(Elemenix.TERRIX, 40));
            map.put("twilightforest:wrought_iron_bar", new Constituents(0, 3, 0, 80, 0, 0));
            map.put("twilightforest:huge_water_lily", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("twilightforest:huge_lily_pad", new Constituents(72, 0, 40, 0, 0, 0));
            map.put("twilightforest:underbrick", Constituents.stone());
            map.put("twilightforest:smoker", new Constituents(80, 0, 10, 0, 30, 30));
            map.put("twilightforest:fire_jet", new Constituents(80, 0, 0, 0, 80, 50));
            map.put("twilightforest:aurora_block", new Constituents(Elemenix.ENERGIX, 24));
            map.put("twilightforest:uberous_soil", new Constituents(86, 34, 0, 0, 0, 16));
            map.put("twilightforest:deadrock", new Constituents(Elemenix.TERRIX, 200));
            map.put("twilightforest:cracked_deadrock", new Constituents(Elemenix.TERRIX, 180));
            map.put("twilightforest:weathered_deadrock", new Constituents(Elemenix.TERRIX, 160));
            map.put("twilightforest:giant_cobblestone", new Constituents(Elemenix.TERRIX, 1536));
            map.put("twilightforest:giant_log", new Constituents(Elemenix.ORGANIX, 6144));
            map.put("twilightforest:giant_leaves", new Constituents(384, 0, 128, 0, 0, 0));
            map.put("twilightforest:giant_obsidian", new Constituents(Elemenix.TERRIX, 7680));
            map.put("twilightforest:trollsteinn", Constituents.stone());
            map.put("twilightforest:castle_brick", Constituents.stone());
            map.put("twilightforest:huge_stalk", new Constituents(96, 0, 30, 0, 0, 0));
            map.put("twilightforest:trollvidr", new Constituents(Elemenix.ORGANIX, 12));
            map.put("twilightforest:unripe_trollber", new Constituents(16, 0, 4, 0, 0, 0));
            map.put("twilightforest:trollber", new Constituents(32, 0, 26, 0, 12, 0));
            map.put("twilightforest:raven_feather", new Constituents(24, 0, 0, 0, 0, 2));
            map.put("twilightforest:maze_map_focus", new Constituents(24, 0, 0, 0, 0, 80));
            map.put("twilightforest:charm_of_life_1", new Constituents(20, 0, 0, 120, 0, 50));
            map.put("twilightforest:charm_of_keeping_1", new Constituents(120, 0, 0, 20, 0, 50));
            map.put("twilightforest:transformation_powder", new Constituents(48, 0, 0, 0, 5, 30));
            map.put("twilightforest:raw_venison", Constituents.rawMeat(8));
            map.put("twilightforest:raw_meef", Constituents.rawMeat(6, 2));
            map.put("twilightforest:maze_wafer", new Constituents(Elemenix.ORGANIX, 50));
            map.put("twilightforest:steeleaf_ingot", new Constituents(100, 0, 0, 540, 0, 200));
            map.put("twilightforest:liveroot", new Constituents(36, 0, 0, 0, 0, 200));
            map.put("twilightforest:liveroot_block", new Constituents(45, 0, 0, 0, 0, 200));
            map.put("twilightforest:ironwood_ingot", new Constituents(18, 0, 0, 136, 0, 100));
            map.put("twilightforest:borer_essence", new Constituents(20, 20, 0, 0, 12, 1));
            map.put("twilightforest:naga_scale", new Constituents(1200, 120, 0, 0, 0, 400));
            map.put("twilightforest:trophy_pedestal", new Constituents(0, 5000, 0, 50, 0, 150));
            map.put("twilightforest:ghast_trap", new Constituents(464, 0, 0, 360, 400, 800));
            map.put("twilightforest:antibuilder", new Constituents(1200, 0, 0, 10000, 900, 5000));
            map.put("twilightforest:locked_vanishing_block", new Constituents(60, 2, 0, 0, 1, 0));
            map.put("twilightforest:tower_key", new Constituents(0, 0, 0, 720, 0, 500));
            map.put("twilightforest:red_thread", new Constituents(42, 0, 0, 0, 5, 0));
            map.put("twilightforest:arctic_fur", new Constituents(36, 0, 4, 0, 0, 0));
            map.put("twilightforest:alpha_yeti_fur", new Constituents(1350, 0, 30, 0, 0, 350));
            map.put("twilightforest:armor_shard", new Constituents(0, 0, 0, 62, 0, 25));
            map.put("twilightforest:knightmetal_block", new Constituents(0, 0, 0, 5022, 0, 2025));
            map.put("twilightforest:diamond_minotaur_axe", new Constituents(24, 62000, 0, 0, 0, 1300));
            map.put("twilightforest:golden_minotaur_axe", new Constituents(24, 0, 0, 1555, 0, 100));
            map.put("twilightforest:fiery_tears", new Constituents(60, 0, 500, 0, 3400, 450));
            map.put("twilightforest:fiery_blood", new Constituents(60, 0, 500, 0, 3400, 450));
            map.put("twilightforest:magic_beans", new Constituents(12288, 0, 0, 0, 0, 100));
            map.put("twilightforest:crown_splinter", new Constituents(0, 0, 0, 5000, 0, 150));
            map.put("twilightforest:exanimate_essence", new Constituents(0, 200, 0, 0, 2000, 100));
            map.put("twilightforest:fluffy_cloud", new Constituents(Elemenix.FLUMIX, 4));
            map.put("twilightforest:wispy_cloud", new Constituents(Elemenix.FLUMIX, 4));
            map.put("twilightforest:rainy_cloud", new Constituents(Elemenix.FLUMIX, 32));
            map.put("twilightforest:snowy_cloud", new Constituents(Elemenix.FLUMIX, 32));
            map.put("twilightforest:greater_potion_flask", new Constituents(Elemenix.TERRIX, 32));
            map.put("twilightforest:brittle_potion_flask", new Constituents(Elemenix.TERRIX, 32));
            map.put("twilightforest:coronation_carpet", new Constituents(Elemenix.ORGANIX, 80));
            map.put("twilightforest:ore_magnet", new Constituents(0, 0, 0, 432, 0, 100));
            map.put("twilightforest:ice_bomb", new Constituents(0, 10, 36, 0, 0, 0));
            map.put("twilightforest:ice_sword", new Constituents(24, 0, 700, 124, 0, 0));
            map.put("twilightforest:ice_bow", new Constituents(72, 0, 700, 124, 0, 0));
            map.put("twilightforest:glass_sword", new Constituents(24, 2400, 0, 0, 0, 10));
            map.put("twilightforest:phantom_helmet", new Constituents(0, 0, 0, 50000, 0, 2400));
            map.put("twilightforest:phantom_chestplate", new Constituents(0, 0, 0, 80000, 0, 3500));
            map.put("twilightforest:triple_bow", new Constituents(72, 0, 0, 2592, 0, 500));
            map.put("twilightforest:ender_bow", new Constituents(72, 0, 0, 2592, 0, 900));
            map.put("twilightforest:seeker_bow", new Constituents(72, 0, 0, 2592, 0, 750));
            map.put("twilightforest:lamp_of_cinders", new Constituents(0, 0, 0, 2916, 0, 2000));
            map.put("twilightforest:emperors_cloth", new Constituents(160, 0, 80, 0, 0, 300));
            map.put("twilightforest:ore_meter", new Constituents(160, 0, 0, 1500, 0, 1200));
            map.put("twilightforest:pocket_watch", new Constituents(0, 24, 0, 1200, 24, 1200));
            map.put("twilightforest:moon_dial", new Constituents(18, 24, 0, 2400, 24, 400));
            map.put("twilightforest:crumble_horn", new Constituents(2400, 0, 0, 0, 0, 2000));
            map.put("twilightforest:peacock_fan", new Constituents(1200, 0, 300, 0, 0, 1000));
            map.put("twilightforest:twilight_scepter", new Constituents(60, 240, 0, 0, 3000, 2000));
            map.put("twilightforest:zombie_scepter", new Constituents(3060, 240, 0, 0, 0, 2000));
            map.put("twilightforest:lifedrain_scepter", new Constituents(60, 240, 3000, 0, 0, 2000));
            map.put("twilightforest:fortification_scepter", new Constituents(60, 240, 0, 3000, 0, 2000));
            map.put("twilightforest:carminite", new Constituents(104, 152, 0, 0, 72, 204));
            map.put("twilightforest:fiery_ingot", new Constituents(60, 0, 500, 216, 3400, 450));
            map.put("twilightforest:hydra_chop", new Constituents(405, 0, 50, 0, 50, 30));
            map.put("twilightforest:experiment_115", new Constituents(115, 115, 115, 115, 115, 115));
            map.put("twilightforest:meef_stroganoff", new Constituents(178, 0, 46, 0, 2, 200));
            map.put("twilightforest:stronghold_shield", new Constituents(0, 60000, 0, 3200, 0, 800));
            map.put("twilightforest:mazebreaker_pickaxe", new Constituents(24, 200, 0, 35000, 0, 5000));
            map.put("twilightforest:skull_chest", new Constituents(0, 600, 0, 0, 0, 10));
            map.put("twilightforest:keepsake_casket", new Constituents(0, 600, 0, 320, 0, 50));
            map.put("twilightforest:chipped_keepsake_casket", new Constituents(0, 480, 0, 256, 0, 40));
            map.put("twilightforest:damaged_keepsake_casket", new Constituents(0, 300, 0, 160, 0, 25));
            return map;
        });

        registerModMappings("mynethersdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("mynethersdelight:powder_cannon", new Constituents(6, 0, 0, 0, 1, 0));
            map.put("mynethersdelight:stripped_powdery_block", new Constituents(54, 0, 0, 0, 9, 0));
            map.put("mynethersdelight:bullet_pepper", new Constituents(24, 0, 0, 0, 12, 0));
            map.put("mynethersdelight:pepper_powder", new Constituents(2, 0, 0, 0, 12, 0));
            map.put("mynethersdelight:hoglin_loin", Constituents.rawMeat(7));
            map.put("mynethersdelight:hoglin_sausage", new Constituents(17, 0, 4, 0, 0, 0));
            map.put("mynethersdelight:ghasta", new Constituents(24, 0, 0, 0, 2, 2));
            map.put("mynethersdelight:ghasmati", new Constituents(22, 0, 0, 0, 2, 2));
            map.put("mynethersdelight:hoglin_hide", new Constituents(Elemenix.ORGANIX, 160));
            map.put("mynethersdelight:strider_slice", new Constituents(36, 0, 6, 0, 2, 0));
            map.put("mynethersdelight:minced_strider", new Constituents(6, 0, 3, 0, 1, 0));
            map.put("mynethersdelight:strider_rock", new Constituents(30, 24, 8, 0, 5, 0));
            map.put("mynethersdelight:strider_egg", new Constituents(30, 5, 8, 0, 3, 0));
            map.put("mynethersdelight:enchanted_golden_egg", new Constituents(30, 0, 8, 10015, 1000, 1000));
            map.put("mynethersdelight:crimson_fungus_colony", new Constituents(225, 0, 85, 0, 0, 0));
            map.put("mynethersdelight:warped_fungus_colony", new Constituents(225, 0, 85, 0, 0, 0));
            map.put("mynethersdelight:resurgent_soil", new Constituents(80, 50, 14, 0, 8, 0));
            map.put("mynethersdelight:resurgent_soil_farmland", new Constituents(80, 50, 14, 0, 8, 0));
            map.put("mynethersdelight:cold_striderloaf", new Constituents(72, 0, 15, 0, 0, 0));
            map.put("mynethersdelight:plate_of_striderloaf", new Constituents(25, 0, 3, 0, 1, 0));
            map.put("mynethersdelight:plate_of_cold_striderloaf", new Constituents(25, 0, 3, 0, 0, 0));
            map.put("mynethersdelight:hot_cream_cone", new Constituents(9, 57, 1, 0, 29, 0));
            map.put("mynethersdelight:hot_wings_bucket", new Constituents(111, 27, 42, 648, 36, 0));
            map.put("mynethersdelight:slices_of_bread", new Constituents(Elemenix.ORGANIX, 20));
            map.put("mynethersdelight:roast_ear", new Constituents(23, 1, 8, 0, 0, 0));
            map.put("mynethersdelight:plate_of_stuffed_hoglin_snout", new Constituents(182, 4, 43, 0, 1, 0));
            map.put("mynethersdelight:plate_of_stuffed_hoglin_ham", new Constituents(158, 3, 39, 0, 1, 0));
            map.put("mynethersdelight:plate_of_stuffed_hoglin", new Constituents(158, 3, 39, 0, 1, 0));
            map.put("mynethersdelight:magma_cake_slice", new Constituents(12, 25, 0, 0, 28, 1));
            map.put("mynethersdelight:hoglin_trophy", new Constituents(286, 120, 0, 432, 0, 0));
            map.put("mynethersdelight:skoglin_trophy", new Constituents(126, 120, 0, 432, 0, 0));
            map.put("mynethersdelight:golden_trophy", new Constituents(126, 120, 0, 6912, 0, 0));
            return map;
        });

        registerModMappings("twilightdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("twilightdelight:mushgloom_colony", new Constituents(90, 0, 30, 0, 10, 0));
            map.put("twilightdelight:experiment_110", new Constituents(110, 110, 110, 110, 110, 110));
            map.put("twilightdelight:experiment_113", new Constituents(113, 113, 113, 113, 113, 113));
            map.put("twilightdelight:raw_tomahawk_smeak", new Constituents(60, 0, 20, 0, 0, 0));
            map.put("twilightdelight:aurora_pie_slice", new Constituents(46, 0, 0, 0, 18, 0));
            map.put("twilightdelight:torchberry_pie_slice", new Constituents(52, 0, 3, 0, 1, 0));
            map.put("twilightdelight:plate_of_fiery_snakes", new Constituents(395, 30, 138, 0, 856, 216));
            map.put("twilightdelight:plate_of_lily_chicken", new Constituents(94, 0, 23, 0, 7, 0));
            map.put("twilightdelight:meef_wellington", new Constituents(70, 4, 11, 0, 1, 0));
            return map;
        });

        registerModMappings("endersdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("endersdelight:mite_crust", new Constituents(6, 0, 0, 0, 0, 1));
            map.put("endersdelight:enderman_sight", new Constituents(16, 0, 0, 0, 0, 12));
            map.put("endersdelight:shulker_mollusk", new Constituents(40, 0, 10, 0, 0, 10));
            map.put("endersdelight:stuffed_shulker_bowl", new Constituents(51, 32, 7, 0, 0, 9));
            map.put("endersdelight:ethereal_saffron", new Constituents(24, 0, 6, 0, 0, 5));
            map.put("endersdelight:amberveil", new Constituents(18, 0, 6, 0, 0, 3));
            map.put("endersdelight:chorusflame", new Constituents(18, 0, 8, 0, 2, 2));
            map.put("endersdelight:voidpepper", new Constituents(24, 0, 6, 0, 0, 3));
            return map;
        });

        registerModMappings("rusticdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("rusticdelight:cotton_boll", new Constituents(Elemenix.ORGANIX, 24));
            map.put("rusticdelight:bell_pepper_green", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("rusticdelight:bell_pepper_red", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("rusticdelight:bell_pepper_yellow", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("rusticdelight:calamari", new Constituents(25, 0, 10, 0, 0, 0));
            map.put("rusticdelight:coffee_beans", new Constituents(Elemenix.ORGANIX, 20));
            map.put("rusticdelight:pancake", new Constituents(41, 0, 2, 0, 0, 0));
            map.put("rusticdelight:honey_pancake", new Constituents(40, 0, 2, 0, 0, 0));
            map.put("rusticdelight:chocolate_pancake", new Constituents(33, 0, 4, 0, 0, 0));
            map.put("rusticdelight:cherry_blossom_pancake", new Constituents(25, 0, 2, 0, 0, 0));
            map.put("rusticdelight:vegetable_pancake", new Constituents(29, 0, 3, 0, 0, 0));
            map.put("rusticdelight:pumpkin_pancake", new Constituents(39, 0, 13, 0, 0, 0));
            map.put("rusticdelight:syrup_cheesecake_slice", new Constituents(59, 0, 10, 0, 0, 0));
            map.put("rusticdelight:cherry_blossom_cheesecake_slice", new Constituents(33, 0, 2, 0, 0, 0));
            return map;
        });

        registerModMappings("jiagureappear", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("jiagureappear:sour_berries", new Constituents(8, 0, 6, 0, 0, 0));
            map.put("jiagureappear:shadow_berries", new Constituents(8, 0, 4, 0, 0, 2));
            map.put("jiagureappear:turtle_plastron", new Constituents(12, 0, 64, 0, 0, 0));
            map.put("jiagureappear:yolime", new Constituents(35, 0, 10, 0, 0, 10));
            map.put("jiagureappear:zucchini", new Constituents(72, 0, 68, 0, 0, 0));
            map.put("#jiagureappear:amethyst_inscriptions", new Constituents(true));
            return map;
        });

        registerModMappings("crittersandcompanions", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("crittersandcompanions:dragonfly_wing", new Constituents(Elemenix.ORGANIX, 16));
            map.put("crittersandcompanions:koi_fish", new Constituents(20, 2, 12, 0, 0, 0));
            map.put("crittersandcompanions:clam", new Constituents(15, 36, 5, 0, 0, 0));
            map.put("crittersandcompanions:pearl", new Constituents(Elemenix.TERRIX, 24));
            map.put("crittersandcompanions:silk", new Constituents(Elemenix.ORGANIX, 24));
            map.put("crittersandcompanions:silk_cocoon", new Constituents(Elemenix.ORGANIX, 72));
            map.put("crittersandcompanions:sea_bunny_slime_bottle", new Constituents(30, 8, 15, 0, 0, 0));
            map.put("crittersandcompanions:koi_fish_bucket", new Constituents(20, 29, 12, 648, 0, 0));
            map.put("crittersandcompanions:sea_bunny_bucket", new Constituents(30, 27, 15, 648, 0, 0));
            map.put("crittersandcompanions:dumbo_octopus_bucket", new Constituents(30, 27, 15, 648, 0, 0));
            return map;
        });

        registerModMappings("dungeonsdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("dungeonsdelight:wormroot_tendrils", new Constituents(Elemenix.ORGANIX, 12));
            map.put("dungeonsdelight:wormroot_stalk", new Constituents(Elemenix.ORGANIX, 48));
            map.put("dungeonsdelight:wormouth", new Constituents(Elemenix.ORGANIX, 144));
            map.put("dungeonsdelight:rotbulb", new Constituents(24, 0, 6, 0, 0, 0));
            map.put("dungeonsdelight:rotbulb_crop", new Constituents(24, 0, 6, 0, 0, 0));
            map.put("dungeonsdelight:rotbulb_plant", new Constituents(42, 0, 8, 0, 0, 0));
            map.put("dungeonsdelight:stained_scrap", new Constituents(18, 0, 0, 270, 0, 9));
            map.put("dungeonsdelight:heap_of_ancient_eggs", new Constituents(54, 40, 30, 0, 20, 20));
            map.put("dungeonsdelight:sniffer_shank", Constituents.rawMeat(8, 2));
            map.put("dungeonsdelight:gritty_flesh", new Constituents(18, 10, 2, 0, 0, 0));
            map.put("dungeonsdelight:brined_flesh", new Constituents(26, 0, 8, 0, 0, 0));
            map.put("dungeonsdelight:spider_meat", Constituents.rawMeat(5));
            map.put("dungeonsdelight:bogged_brain", new Constituents(26, 0, 12, 0, 0, 0));
            map.put("dungeonsdelight:silverfish_abdomen", new Constituents(12, 2, 2, 0, 0, 0));
            map.put("dungeonsdelight:ghast_tentacle", new Constituents(24, 0, 0, 0, 2, 2));
            map.put("dungeonsdelight:fried_ghast_calamari", new Constituents(12, 0, 0, 0, 3, 1));
            map.put("dungeonsdelight:ancient_egg", new Constituents(10, 8, 6, 0, 2, 2));
            map.put("dungeonsdelight:soft_serve_sniffer_egg", new Constituents(70, 16, 12, 0, 16, 0));
            map.put("dungeonsdelight:polterghast_pizza_slice", new Constituents(32, 0, 8, 0, 2, 2));
            map.put("dungeonsdelight:candied_silverfish_sucker", new Constituents(64, 300, 11, 0, 0, 0));
            map.put("dungeonsdelight:candied_vex_sucker", new Constituents(40, 300, 10, 0, 0, 10));
            map.put("dungeonsdelight:glow_berry_gelatin", new Constituents(34, 6, 4, 0, 18, 1));
            map.put("dungeonsdelight:ossobuco", new Constituents(36, 12, 6, 0, 0, 0));
            map.put("dungeonsdelight:guardian_angel", new Constituents(57, 6, 21, 96, 19, 1));
            map.put("dungeonsdelight:silverfish_and_chips", new Constituents(47, 6, 7, 0, 16, 1));
            map.put("dungeonsdelight:bug_chops", Constituents.rawMeat(8));
            map.put("dungeonsdelight:monster_cake_slice", new Constituents(45, 1, 11, 0, 0, 1));
            map.put("dungeonsdelight:spider_pie_slice", new Constituents(123, 0, 20, 0, 0, 1));
            map.put("dungeonsdelight:sculk_tart_slice", new Constituents(35, 6, 4, 0, 2, 2));
            return map;
        });

        registerModMappings("create", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("create:zinc_ore", new Constituents(Elemenix.TERRIX, 102));
            map.put("create:deepslate_zinc_ore", new Constituents(Elemenix.TERRIX, 102));
            map.put("#create:packages", new Constituents(Elemenix.ORGANIX, 24));
            map.put("create:raw_zinc", new Constituents(Elemenix.TERRIX, 78));
            map.put("create:zinc_ingot", new Constituents(0, 6, 0, 72, 0, 0));
            map.put("create:andesite_alloy", new Constituents(0, 28, 0, 8, 0, 0));
            map.put("create:andesite_casing", new Constituents(96, 28, 0, 8, 0, 0));
            map.put("create:brass_casing", new Constituents(96, 15, 0, 72, 0, 0));
            map.put("create:copper_casing", new Constituents(96, 24, 0, 72, 0, 0));
            map.put("create:powdered_obsidian", new Constituents(Elemenix.TERRIX, 30));
            map.put("create:sturdy_sheet", new Constituents(Elemenix.TERRIX, 150));
            map.put("create:railway_casing", new Constituents(96, 165, 0, 72, 0, 0));
            map.put("create:cinder_flour", new Constituents(10, 0, 0, 0, 1, 0));
            map.put("create:precision_mechanism", new Constituents(72, 15, 0, 460, 0, 0));
            map.put("create:stressometer", new Constituents(96, 82, 0, 872, 6, 0));
            map.put("create:wheat_flour", new Constituents(Elemenix.ORGANIX, 12));
            map.put("create:dough", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("create:blaze_burner", new Constituents(0, 55, 0, 864, 217, 0));
            map.put("create:blaze_cake", new Constituents(36, 38, 6, 0, 192, 0));
            map.put("create:brass_ingot", new Constituents(0, 9, 0, 72, 0, 0));
            map.put("create:attribute_filter", new Constituents(96, 2, 0, 16, 0, 0));
            map.put("create:experience_nugget", new Constituents(0, 0, 0, 0, 2, 2));
            map.put("create:track", new Constituents(0, 12, 0, 16, 0, 0));
            map.put("create:cardboard", new Constituents(Elemenix.ORGANIX, 24));
            map.put("create:haunted_bell", new Constituents(0, 90, 0, 720, 0, 5));
            map.put("create:bar_of_chocolate", new Constituents(39, 0, 5, 0, 0, 0));
            map.put("create:sweet_roll", new Constituents(Elemenix.ORGANIX, 73));
            map.put("create:chocolate_glazed_berries", new Constituents(47, 0, 11, 0, 0, 0));
            map.put("create:honeyed_apple", new Constituents(92, 0, 15, 0, 0, 0));
            map.put("create:builders_tea", new Constituents(3, 8, 6, 0, 2, 0));
            map.put("create:asurine", new Constituents(0, 20, 0, 4, 0, 0));
            map.put("create:crimsite", new Constituents(0, 20, 0, 4, 0, 0));
            map.put("create:limestone", Constituents.stone());
            map.put("create:ochrum", new Constituents(0, 20, 0, 4, 0, 0));
            map.put("create:veridium", new Constituents(0, 20, 0, 4, 0, 0));
            return map;
        });

        registerModMappings("eternal_starlight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("#c:ores/atalphaite", new Constituents(0, 124, 0, 0, 96, 0));
            map.put("#c:ores/starlit_diamond", new Constituents(0, 41024, 0, 0, 0, 1200));
            map.put("#c:ores/swamp_silver", new Constituents(0, 24, 0, 3456, 0, 45));
            map.put("#c:ores/malarite", new Constituents(0, 8024, 0, 0, 0, 100));
            map.put("#c:ores/saltpeter", new Constituents(0, 120, 0, 0, 48, 0));
            map.put("eternal_starlight:saltpeter_powder", new Constituents(0, 96, 0, 0, 48, 0));
            map.put("eternal_starlight:swamp_silver_ingot", new Constituents(0, 0, 0, 3456, 0, 45));
            map.put("eternal_starlight:malarite", new Constituents(0, 8000, 0, 0, 0, 100));
            map.put("eternal_starlight:torreya_vines", new Constituents(6, 0, 2, 0, 4, 0));
            map.put("eternal_starlight:algaleaves", new Constituents(5, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:hanging_algaleaves", new Constituents(5, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:glowing_voidstone", new Constituents(0, 22, 0, 0, 5, 0));
            map.put("eternal_starlight:eternal_ice", new Constituents(Elemenix.FLUMIX, 60));
            map.put("eternal_starlight:eternal_ice_atalphaite_ore", new Constituents(0, 100, 60, 0, 96, 0));
            map.put("eternal_starlight:eternal_ice_starlit_diamond_ore", new Constituents(0, 41000, 60, 0, 96, 1200));
            map.put("eternal_starlight:eternal_ice_saltpeter_ore", new Constituents(0, 96, 60, 0, 48, 0));
            map.put("eternal_starlight:eternal_ice_redstone_ore", new Constituents(0, 18, 60, 0, 6, 0));
            map.put("eternal_starlight:icicle", new Constituents(Elemenix.FLUMIX, 24));
            map.put("eternal_starlight:haze_ice", new Constituents(0, 12, 48, 0, 0, 0));
            map.put("eternal_starlight:haze_ice_atalphaite_ore", new Constituents(0, 112, 48, 0, 96, 0));
            map.put("eternal_starlight:haze_ice_starlit_diamond_ore", new Constituents(0, 41012, 48, 0, 96, 1200));
            map.put("eternal_starlight:haze_ice_saltpeter_ore", new Constituents(0, 108, 48, 0, 48, 0));
            map.put("eternal_starlight:haze_ice_redstone_ore", new Constituents(0, 30, 48, 0, 6, 0));
            map.put("eternal_starlight:ashen_snow", new Constituents(0, 4, 12, 0, 0, 0));
            map.put("eternal_starlight:ashen_snowball", new Constituents(0, 2, 6, 0, 0, 0));
            map.put("eternal_starlight:aethersent_ingot", new Constituents(0, 0, 0, 252, 0, 225));
            map.put("eternal_starlight:aethersent_nugget", new Constituents(0, 0, 0, 28, 0, 25));
            map.put("eternal_starlight:raw_aethersent", new Constituents(0, 252, 0, 0, 0, 225));
            map.put("eternal_starlight:creteor_hide", new Constituents(40, 0, 0, 0, 12, 45));
            map.put("eternal_starlight:starlit_diamond", new Constituents(0, 41250, 0, 0, 0, 1200));
            map.put("eternal_starlight:atalphaite", new Constituents(0, 100, 0, 0, 96, 0));
            map.put("eternal_starlight:dusted_gravel", new Constituents(Elemenix.TERRIX, 24));
            map.put("eternal_starlight:dusted_shard", new Constituents(Elemenix.TERRIX, 24));
            map.put("eternal_starlight:stellagmite", Constituents.stone());
            map.put("eternal_starlight:molten_stellagmite", new Constituents(0, 20, 4, 0, 2, 0));
            map.put("eternal_starlight:abysslate", Constituents.stone());
            map.put("eternal_starlight:abyssal_magma_block", new Constituents(0, 48, 0, 0, 120, 16));
            map.put("eternal_starlight:abyssal_geyser", new Constituents(0, 48, 0, 0, 20, 0));
            map.put("eternal_starlight:springstone", Constituents.stone());
            map.put("eternal_starlight:thermabysslate", new Constituents(0, 24, 0, 0, 2, 0));
            map.put("eternal_starlight:thermabyssal_magma_block", new Constituents(0, 48, 0, 0, 122, 16));
            map.put("eternal_starlight:thermabyssal_geyser", new Constituents(0, 48, 0, 0, 22, 0));
            map.put("eternal_starlight:cryobysslate", Constituents.stone());
            map.put("eternal_starlight:cryobysslate_magma_block", new Constituents(0, 48, 0, 0, 110, 16));
            map.put("eternal_starlight:cryobysslate_geyser", new Constituents(0, 48, 0, 0, 18, 0));
            map.put("eternal_starlight:thermal_springstone", new Constituents(0, 64, 0, 0, 80, 200));
            map.put("eternal_starlight:mossy_dusted_gravel", new Constituents(6, 24, 0, 0, 0, 0));
            map.put("eternal_starlight:glowing_mossy_dusted_gravel", new Constituents(6, 24, 0, 0, 2, 0));
            map.put("eternal_starlight:tooth_of_hunger", new Constituents(5, 24, 0, 0, 0, 100));
            map.put("eternal_starlight:nightfall_mud", new Constituents(6, 18, 4, 0, 0, 0));
            map.put("eternal_starlight:glowing_nightfall_mud", new Constituents(6, 18, 4, 0, 2, 0));
            map.put("eternal_starlight:nightfall_dirt", new Constituents(6, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:nightfall_farmland", new Constituents(6, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:nightfall_dirt_path", new Constituents(6, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:nightfall_grass_block", new Constituents(10, 18, 2, 0, 0, 0));
            map.put("eternal_starlight:tenacious_nightfall_grass_block", new Constituents(12, 18, 4, 0, 0, 0));
            map.put("eternal_starlight:nightfall_podzol", new Constituents(12, 16, 2, 0, 0, 0));
            map.put("eternal_starlight:fantasy_grass_block", new Constituents(10, 18, 2, 0, 0, 0));
            map.put("eternal_starlight:nightfall_grass_carpet", new Constituents(4, 0, 4, 0, 0, 0));
            map.put("eternal_starlight:lunar_berries", new Constituents(8, 0, 4, 0, 2, 0));
            map.put("eternal_starlight:abyssal_fruit", new Constituents(8, 0, 6, 0, 2, 0));
            map.put("eternal_starlight:orbflora", new Constituents(18, 0, 10, 0, 10, 0));
            map.put("eternal_starlight:orbflora_light", new Constituents(24, 0, 12, 0, 40, 0));
            map.put("eternal_starlight:nightfan_bush", Constituents.flower());
            map.put("eternal_starlight:moonlight_bush", Constituents.flower());
            map.put("eternal_starlight:pink_rose_bush", Constituents.flowerLarge());
            map.put("eternal_starlight:gladespike", Constituents.flower());
            map.put("eternal_starlight:vividstalk", Constituents.flower());
            map.put("eternal_starlight:tall_gladespike", Constituents.flowerLarge());
            map.put("eternal_starlight:night_sprouts", Constituents.grassVineLeaves());
            map.put("eternal_starlight:glowing_night_sprouts", new Constituents(6, 0, 2, 0, 2, 0));
            map.put("eternal_starlight:small_night_sprouts", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:small_glowing_night_sprouts", new Constituents(3, 0, 1, 0, 1, 0));
            map.put("eternal_starlight:lunar_grass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:glowing_lunar_grass", new Constituents(6, 0, 2, 0, 2, 0));
            map.put("eternal_starlight:lunar_bush", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("eternal_starlight:glowing_lunar_bush", new Constituents(12, 0, 4, 0, 4, 0));
            map.put("eternal_starlight:crescent_grass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:glowing_crescent_grass", new Constituents(6, 0, 2, 0, 2, 0));
            map.put("eternal_starlight:tall_crescent_grass", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("eternal_starlight:tall_glowing_crescent_grass", new Constituents(12, 0, 4, 0, 4, 0));
            map.put("eternal_starlight:parasol_grass", new Constituents(8, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:glowing_parasol_grass", new Constituents(8, 0, 3, 0, 2, 0));
            map.put("eternal_starlight:lunar_reed", new Constituents(12, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:glowing_mushroom", new Constituents(18, 0, 6, 0, 2, 0));
            map.put("eternal_starlight:glowing_mushroom_block", new Constituents(36, 0, 12, 0, 4, 0));
            map.put("eternal_starlight:glowing_mushroom_stem", new Constituents(36, 0, 12, 0, 4, 0));
            map.put("eternal_starlight:bouldershroom", new Constituents(18, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:bouldershroom_block", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:bouldershroom_stem", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:bouldershroom_roots", new Constituents(18, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:cave_moss", Constituents.grassVineLeaves());
            map.put("eternal_starlight:marimold", new Constituents(18, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:marimold_block", new Constituents(36, 0, 24, 0, 0, 0));
            map.put("eternal_starlight:marimold_stem", new Constituents(36, 0, 24, 0, 0, 0));
            map.put("eternal_starlight:fantabud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:green_fantabud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:fantafern", Constituents.grassVineLeaves());
            map.put("eternal_starlight:green_fantafern", Constituents.grassVineLeaves());
            map.put("eternal_starlight:fantagrass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:green_fantagrass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:hanging_fantagrass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:orange_scarlet_bud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:purple_scarlet_bud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:red_scarlet_bud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:scarlet_grass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:mauve_fern", Constituents.grassVineLeaves());
            map.put("eternal_starlight:amaramber_grass", new Constituents(18, 0, 8, 0, 1, 0));
            map.put("eternal_starlight:amaramber_bush", new Constituents(18, 0, 4, 0, 2, 0));
            map.put("eternal_starlight:red_starlight_crystal_shard", new Constituents(0, 300, 0, 0, 0, 60));
            map.put("eternal_starlight:blue_starlight_crystal_shard", new Constituents(0, 300, 0, 0, 0, 60));
            map.put("eternal_starlight:red_starlight_crystal_cluster", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:blue_starlight_crystal_cluster", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:red_starlight_crystal_block", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:blue_starlight_crystal_block", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:blooming_red_starlight_crystal_cluster", new Constituents(18, 1200, 8, 0, 0, 240));
            map.put("eternal_starlight:blooming_starlight_crystal_cluster", new Constituents(18, 1200, 8, 0, 0, 240));
            map.put("eternal_starlight:dead_lunar_bush", new Constituents(Elemenix.ORGANIX, 12));
            map.put("eternal_starlight:sunset_thornbloom", new Constituents(0, 18, 0, 0, 32, 0));
            map.put("eternal_starlight:amethysia_grass", new Constituents(8, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:lunaris_cactus", new Constituents(18, 0, 10, 0, 0, 10));
            map.put("eternal_starlight:lunaris_cactus_fruit", new Constituents(18, 0, 10, 0, 0, 10));
            map.put("eternal_starlight:carved_lunaris_cactus_fruit", new Constituents(16, 0, 8, 0, 0, 10));
            map.put("eternal_starlight:lunaris_cactus_gel", new Constituents(18, 0, 2, 0, 0, 10));
            map.put("eternal_starlight:red_crystalfleur_vine", Constituents.grassVineLeaves());
            map.put("eternal_starlight:blue_crystalfleur_vine", Constituents.grassVineLeaves());
            map.put("eternal_starlight:red_crystal_moss_block", new Constituents(6, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:blue_crystal_moss_block", new Constituents(6, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:moonlight_lily_pad", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("eternal_starlight:starlit_lily_pad", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("eternal_starlight:moonlight_duckweed", new Constituents(6, 0, 8, 0, 0, 0));
            map.put("eternal_starlight:spiral_kelp", Constituents.seagrass());
            map.put("eternal_starlight:sea_rosa", Constituents.seagrass());
            map.put("eternal_starlight:wick_grass", Constituents.seagrass());
            map.put("eternal_starlight:lumenstem", new Constituents(18, 0, 8, 0, 3, 0));
            map.put("eternal_starlight:glacite", new Constituents(0, 12, 120, 0, 0, 200));
            map.put("eternal_starlight:glacite_shard", new Constituents(0, 0, 120, 0, 0, 200));
            map.put("eternal_starlight:rookfish", Constituents.rawMeat(7));
            map.put("eternal_starlight:rookfish_air_sac", new Constituents(24, 0, 8, 0, 0, 0));
            map.put("eternal_starlight:luminofish", Constituents.rawFish(6));
            map.put("eternal_starlight:luminaris", Constituents.rawFish(6));
            map.put("eternal_starlight:white_yeti_fur", new Constituents(Elemenix.ORGANIX, 96));
            map.put("eternal_starlight:raw_amaramber", new Constituents(360, 0, 0, 0, 10, 20));
            map.put("eternal_starlight:amaramber_ingot", new Constituents(180, 12, 0, 0, 5, 10));
            map.put("eternal_starlight:keeper_armor_trim_smithing_template", new Constituents(0, 24, 0, 24192, 0, 315));
            map.put("eternal_starlight:forge_armor_trim_smithing_template", new Constituents(0, 24, 0, 24192, 0, 315));
            map.put("eternal_starlight:blooming_armor_trim_smithing_template", new Constituents(84, 24, 0, 0, 35, 50));
            map.put("eternal_starlight:twining_armor_trim_smithing_template", new Constituents(84, 24, 0, 0, 35, 50));
            map.put("eternal_starlight:aurora_deer_steak", Constituents.rawMeat(8));
            map.put("eternal_starlight:ratlin_meat", Constituents.rawMeat(6));
            map.put("eternal_starlight:shadow_snail_meat", Constituents.rawMeat(5, 4));
            map.put("eternal_starlight:aurora_deer_antler", new Constituents(1200, 0, 0, 0, 0, 500));
            map.put("eternal_starlight:shadow_snail_shell", new Constituents(0, 72, 16, 0, 0, 0));
            map.put("eternal_starlight:frozen_tube", new Constituents(0, 8, 64, 12, 0, 0));
            map.put("eternal_starlight:shivering_gel", new Constituents(18, 0, 10, 0, 0, 16));
            map.put("eternal_starlight:nightfall_spider_eye", new Constituents(32, 8, 8, 0, 0, 5));
            map.put("eternal_starlight:gleech_egg", new Constituents(32, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:tangled_skull", new Constituents(50, 360, 0, 0, 0, 400));
            map.put("eternal_starlight:crystallized_sand", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:circulush", Constituents.seagrass());
            map.put("eternal_starlight:stonett", Constituents.seagrass());
            map.put("eternal_starlight:luminis", Constituents.seagrass());
            map.put("eternal_starlight:glowlis", Constituents.seagrass());
            map.put("eternal_starlight:glowreed", Constituents.seagrass());
            map.put("eternal_starlight:starlight_seagrass", Constituents.seagrass());
            map.put("eternal_starlight:jingling_pickle", new Constituents(18, 0, 12, 0, 5, 0));
            map.put("eternal_starlight:dead_tentacles_coral_block", new Constituents(36, 16, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_golden_coral_block", new Constituents(36, 16, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_crystallum_coral_block", new Constituents(36, 16, 0, 0, 0, 0));
            map.put("eternal_starlight:tentacles_coral_block", new Constituents(36, 16, 16, 0, 0, 0));
            map.put("eternal_starlight:golden_coral_block", new Constituents(36, 16, 16, 0, 0, 0));
            map.put("eternal_starlight:crystallum_coral_block", new Constituents(36, 16, 16, 0, 0, 0));
            map.put("eternal_starlight:dead_tentacles_coral", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_golden_coral", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_crystallum_coral", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:tentacles_coral", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:golden_coral", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:crystallum_coral", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:dead_tentacles_coral_fan", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_golden_coral_fan", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_crystallum_coral_fan", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:tentacles_coral_fan", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:golden_coral_fan", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:crystallum_coral_fan", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:velvetumoss", new Constituents(140, 0, 40, 0, 0, 0));
            map.put("eternal_starlight:velvetumoss_ball", new Constituents(18, 0, 5, 0, 0, 0));
            map.put("eternal_starlight:velvetumoss_villi", new Constituents(7, 0, 2, 0, 0, 0));
            map.put("eternal_starlight:red_velvetumoss", new Constituents(70, 0, 20, 0, 0, 0));
            map.put("eternal_starlight:red_velvetumoss_villi", new Constituents(7, 0, 2, 0, 0, 0));
            map.put("eternal_starlight:red_velvetumoss_flower", new Constituents(24, 0, 12, 0, 0, 16));
            map.put("eternal_starlight:crystallized_lunar_grass", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:red_crystal_roots", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:blue_crystal_roots", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:twilvewyrm_herb", Constituents.flowerLarge());
            map.put("eternal_starlight:stellafly_bush", Constituents.flowerLarge());
            map.put("eternal_starlight:glimmerflt_bush", new Constituents(36, 0, 16, 0, 10, 0));
            map.put("eternal_starlight:pungency_fruit_seeds", new Constituents(Elemenix.ORGANIX, 5));
            map.put("eternal_starlight:pungency_fruit", new Constituents(22, 0, 10, 0, 0, 0));
            map.put("eternal_starlight:seeds_launcher", new Constituents(1200, 0, 648, 0, 0, 150));
            map.put("eternal_starlight:rotten_flesh_jerky", new Constituents(18, 0, 2, 0, 0, 0));
            map.put("eternal_starlight:starfire_bird_nest", new Constituents(240, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:starfire", new Constituents(0, 0, 0, 0, 500, 200));
            map.put("eternal_starlight:drying_rack", new Constituents(Elemenix.ORGANIX, 128));
            map.put("eternal_starlight:raw_flowglaze", new Constituents(0, 8, 0, 0, 500, 200));
            map.put("eternal_starlight:pungency_fruit_upgrade_smithing_template", new Constituents(0, 1348, 0, 0, 1424, 1400));
            map.put("eternal_starlight:starfire_upgrade_smithing_template", new Constituents(14, 56018, 10, 8, 2, 800));
            map.put("eternal_starlight:flowglaze_upgrade_smithing_template", new Constituents(0, 0, 900, 0, 0, 1400));
            map.put("eternal_starlight:ether_bucket", new Constituents(0, 27, 20, 648, 20, 0));
            map.put("eternal_starlight:thioquartz_shard", new Constituents(Elemenix.TERRIX, 24));
            map.put("eternal_starlight:thioquartz_cluster", new Constituents(Elemenix.TERRIX, 96));
            map.put("eternal_starlight:toxite", new Constituents(4, 20, 0, 0, 0, 0));
            map.put("eternal_starlight:rookfish_bucket", new Constituents(35, 27, 8, 648, 0, 0));
            map.put("eternal_starlight:luminofish_bucket", new Constituents(30, 29, 8, 648, 0, 0));
            map.put("eternal_starlight:luminaris_bucket", new Constituents(30, 29, 8, 648, 0, 0));
            map.put("eternal_starlight:starlight_silver_coin", new Constituents(0, 0, 0, 300, 0, 2));
            map.put("eternal_starlight:golem_steel_ingot", new Constituents(0, 99, 0, 8100, 0, 99));
            map.put("eternal_starlight:oxidized_golem_steel_ingot", new Constituents(0, 5697, 0, 2502, 0, 99));
            map.put("eternal_starlight:tenacious_petal", new Constituents(11520, 0, 120, 0, 0, 412));
            map.put("eternal_starlight:tenacious_vine", new Constituents(11520, 0, 80, 0, 0, 388));
            map.put("eternal_starlight:trapped_soul", new Constituents(0, 120, 1200, 0, 0, 100));
            map.put("eternal_starlight:shadegrieve", new Constituents(24, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:blooming_shadegrieve", new Constituents(24, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:lunar_vine", Constituents.grassVineLeaves());
            map.put("eternal_starlight:shattered_sword", new Constituents(0, 12, 0, 6912, 0, 500));
            map.put("eternal_starlight:shattered_sword_blade", new Constituents(0, 0, 0, 6912, 0, 500));
            map.put("eternal_starlight:golem_steel_jet", new Constituents(0, 782, 0, 100008, 0, 792));
            map.put("eternal_starlight:oxidized_golem_steel_jet", new Constituents(0, 80784, 0, 20216, 0, 792));
            map.put("eternal_starlight:battleaxe_pendant", new Constituents(144, 0, 0, 648, 0, 600));
            map.put("eternal_starlight:warhammer_pendant", new Constituents(144, 0, 0, 648, 0, 600));
            map.put("eternal_starlight:crescent_pendant", new Constituents(144, 1296, 0, 0, 0, 600));
            map.put("eternal_starlight:butterfly_wings_amulet", new Constituents(144, 120, 1056, 120, 0, 600));
            map.put("eternal_starlight:fungus_amulet", new Constituents(1440, 0, 0, 0, 0, 600));
            map.put("eternal_starlight:pearl_necklace", new Constituents(144, 1296, 0, 0, 0, 600));
            return map;
        });

        registerModMappings("iceandfire", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("iceandfire:manuscript", new Constituents(20, 8, 0, 0, 0, 0));
            map.put("iceandfire:fire_lily", new Constituents(18, 0, 8, 0, 12, 0));
            map.put("iceandfire:frost_lily", new Constituents(18, 0, 20, 0, 0, 0));
            map.put("iceandfire:lightning_lily", new Constituents(18, 0, 8, 0, 12, 0));
            map.put("iceandfire:sapphire", new Constituents(Elemenix.TERRIX, 800));
            map.put("iceandfire:sapphire_ore", new Constituents(Elemenix.TERRIX, 824));
            map.put("iceandfire:ectoplasm", new Constituents(0, 0, 32, 0, 0, 12));
            map.put("iceandfire:dragonbone", new Constituents(24, 1200, 0, 0, 0, 50));
            map.put("iceandfire:witherbone", new Constituents(0, 48, 0, 0, 0, 10));
            map.put("#iceandfire:scales/dragon/fire", new Constituents(4000, 0, 0, 0, 180, 400));
            map.put("#iceandfire:scales/dragon/ice", new Constituents(4000, 0, 180, 0, 0, 400));
            map.put("#iceandfire:scales/dragon/lightning", new Constituents(4000, 0, 0, 0, 180, 400));
            map.put("#iceandfire:scales/sea_serpent", new Constituents(3000, 0, 0, 0, 0, 250));
            map.put("#iceandfire:dragon_skulls", new Constituents(0, 400, 0, 0, 0, 120));
            map.put("#iceandfire:mob_skulls", new Constituents(0, 300, 0, 0, 0, 100));
            map.put("iceandfire:fire_dragon_flesh", new Constituents(50, 0, 12, 0, 40, 0));
            map.put("iceandfire:ice_dragon_flesh", new Constituents(50, 0, 52, 0, 0, 0));
            map.put("iceandfire:lightning_dragon_flesh", new Constituents(50, 0, 12, 0, 40, 0));
            map.put("iceandfire:fire_dragon_heart", new Constituents(600, 0, 120, 0, 250, 120));
            map.put("iceandfire:ice_dragon_heart", new Constituents(600, 0, 370, 0, 0, 120));
            map.put("iceandfire:lightning_dragon_heart", new Constituents(600, 0, 120, 0, 250, 120));
            map.put("iceandfire:fire_dragon_blood", new Constituents(4000, 0, 0, 0, 250, 800));
            map.put("iceandfire:ice_dragon_blood", new Constituents(4000, 0, 250, 0, 0, 800));
            map.put("iceandfire:lightning_dragon_blood", new Constituents(4000, 0, 0, 0, 250, 800));
            map.put("iceandfire:hippogryph_talon", new Constituents(160, 0, 0, 0, 0, 40));
            map.put("iceandfire:hippogryph_egg", new Constituents(234, 128, 32, 0, 0, 0));
            map.put("iceandfire:stone_statue", new Constituents(Elemenix.TERRIX, 240));
            map.put("iceandfire:pixie_dust", new Constituents(10, 0, 0, 0, 0, 16));
            map.put("iceandfire:pixie_wings", new Constituents(160, 0, 0, 0, 0, 200));
            map.put("iceandfire:shiny_scales", new Constituents(50, 0, 0, 0, 0, 5));
            map.put("iceandfire:siren_tear", new Constituents(20, 0, 320, 0, 0, 450));
            map.put("iceandfire:hippocampus_fin", new Constituents(320, 0, 0, 0, 0, 250));
            map.put("iceandfire:deathworm_chitin_yellow", new Constituents(60, 60, 0, 0, 0, 10));
            map.put("iceandfire:deathworm_chitin_red", new Constituents(60, 60, 0, 0, 0, 10));
            map.put("iceandfire:deathworm_chitin_white", new Constituents(60, 60, 0, 0, 0, 10));
            map.put("iceandfire:deathworm_egg", new Constituents(240, 0, 32, 0, 0, 0));
            map.put("iceandfire:deathworm_egg_giant", new Constituents(480, 0, 64, 0, 0, 0));
            map.put("iceandfire:deathworm_tounge", new Constituents(360, 180, 0, 0, 0, 400));
            map.put("iceandfire:rotten_egg", new Constituents(200, 100, 32, 0, 0, 0));
            map.put("iceandfire:cockatrice_eye", new Constituents(160, 0, 100, 0, 0, 350));
            map.put("iceandfire:cyclops_eye", new Constituents(1200, 0, 800, 0, 0, 400));
            map.put("iceandfire:stymphalian_bird_feather", new Constituents(16, 0, 0, 72, 0, 0));
            map.put("iceandfire:troll_tusk", new Constituents(10, 40, 0, 0, 0, 32));
            map.put("iceandfire:amphithere_feather", new Constituents(64, 0, 0, 0, 0, 10));
            map.put("iceandfire:sea_serpent_fang", new Constituents(16, 44, 0, 0, 0, 12));
            map.put("iceandfire:hydra_fang", new Constituents(20, 100, 0, 0, 0, 20));
            map.put("iceandfire:hydra_heart", new Constituents(12000, 0, 1250, 0, 0, 1200));
            map.put("iceandfire:ghost_ingot", new Constituents(0, 0, 640, 210, 0, 1000));
            map.put("iceandfire:troll_leather_mountain", new Constituents(150, 5, 0, 0, 0, 150));
            map.put("iceandfire:troll_leather_forest", new Constituents(155, 0, 0, 0, 0, 150));
            map.put("iceandfire:troll_leather_frost", new Constituents(150, 0, 5, 0, 0, 150));
            map.put("iceandfire:dread_shard", new Constituents(Elemenix.TERRIX, 12));
            map.put("iceandfire:dread_key", new Constituents(0, 0, 0, 1560, 0, 400));
            map.put("iceandfire:gorgon_head", new Constituents(12500, 480, 1000, 0, 0, 1200));
            map.put("iceandfire:dreadwood_leaves", Constituents.grassVineLeaves());
            map.put("iceandfire:dreadwood_sapling", new Constituents(64, 0, 24, 0, 0, 0));
            map.put("iceandfire:burnt_torch", new Constituents(17, 9, 0, 0, 0, 0));
            map.put("iceandfire:weezer_blue_album", new Constituents(0, 0, 0, 0, 19, 92));
            map.put("iceandfire:dragonsteel_fire_ingot", new Constituents(4000, 9, 0, 216, 250, 800));
            map.put("iceandfire:dragonsteel_ice_ingot", new Constituents(4000, 9, 250, 216, 0, 800));
            map.put("iceandfire:dragonsteel_lightning_ingot", new Constituents(4000, 9, 0, 216, 250, 800));
            map.put("iceandfire:chared_dirt", new Constituents(Elemenix.TERRIX, 20));
            map.put("iceandfire:chared_dirt_path", new Constituents(Elemenix.TERRIX, 20));
            map.put("iceandfire:chared_grass", new Constituents(Elemenix.TERRIX, 20));
            map.put("iceandfire:chared_stone", Constituents.stone());
            map.put("iceandfire:chared_cobblestone", Constituents.stone());
            map.put("iceandfire:chared_gravel", Constituents.stone());
            map.put("iceandfire:frozen_dirt", new Constituents(6, 18, 5, 0, 0, 0));
            map.put("iceandfire:frozen_dirt_path", new Constituents(6, 18, 5, 0, 0, 0));
            map.put("iceandfire:frozen_grass", new Constituents(10, 18, 7, 0, 0, 0));
            map.put("iceandfire:frozen_stone", new Constituents(0, 24, 5, 0, 0, 0));
            map.put("iceandfire:frozen_cobblestone", new Constituents(0, 24, 5, 0, 0, 0));
            map.put("iceandfire:frozen_gravel", new Constituents(0, 24, 5, 0, 0, 0));
            map.put("iceandfire:frozen_splinters", new Constituents(12, 0, 5, 0, 0, 0));
            map.put("iceandfire:dragon_ice", new Constituents(Elemenix.FLUMIX, 45));
            map.put("iceandfire:crackled_dirt", new Constituents(Elemenix.TERRIX, 20));
            map.put("iceandfire:crackled_dirt_path", new Constituents(Elemenix.TERRIX, 20));
            map.put("iceandfire:crackled_grass", new Constituents(Elemenix.TERRIX, 20));
            map.put("iceandfire:crackled_stone", Constituents.stone());
            map.put("iceandfire:crackled_cobblestone", Constituents.stone());
            map.put("iceandfire:crackled_gravel", Constituents.stone());
            map.put("iceandfire:pixie_house_mushroom_red", new Constituents(96, 12, 0, 0, 0, 0));
            map.put("iceandfire:pixie_house_mushroom_brown", new Constituents(96, 12, 0, 0, 0, 0));
            map.put("iceandfire:pixie_house_oak", new Constituents(96, 12, 0, 0, 0, 0));
            map.put("iceandfire:pixie_house_birch", new Constituents(96, 12, 0, 0, 0, 0));
            map.put("iceandfire:pixie_house_spruce", new Constituents(96, 12, 0, 0, 0, 0));
            map.put("iceandfire:pixie_house_dark_oak", new Constituents(96, 12, 0, 0, 0, 0));
            map.put("iceandfire:pixie_jar_0", new Constituents(144, 56, 60, 0, 0, 400));
            map.put("iceandfire:pixie_jar_1", new Constituents(144, 56, 60, 0, 0, 400));
            map.put("iceandfire:pixie_jar_2", new Constituents(144, 56, 60, 0, 0, 400));
            map.put("iceandfire:pixie_jar_3", new Constituents(144, 56, 60, 0, 0, 400));
            map.put("iceandfire:pixie_jar_4", new Constituents(144, 56, 60, 0, 0, 400));
            map.put("iceandfire:dread_sword", new Constituents(12, 240, 0, 48, 0, 0));
            map.put("iceandfire:dread_knight_sword", new Constituents(12, 4800, 0, 96000, 0, 500));
            map.put("iceandfire:lich_staff", new Constituents(48, 70000, 250, 0, 0, 500));
            map.put("iceandfire:troll_weapon_axe", new Constituents(3200, 8000, 0, 0, 0, 400));
            map.put("iceandfire:troll_weapon_column", new Constituents(0, 11200, 0, 0, 0, 400));
            map.put("iceandfire:troll_weapon_column_forest", new Constituents(200, 11000, 0, 0, 0, 400));
            map.put("iceandfire:troll_weapon_column_frost", new Constituents(0, 10000, 1200, 0, 0, 400));
            map.put("iceandfire:troll_weapon_hammer", new Constituents(3200, 8000, 0, 0, 0, 400));
            map.put("iceandfire:troll_weapon_trunk", new Constituents(11200, 0, 0, 0, 0, 400));
            map.put("iceandfire:troll_weapon_trunk_frost", new Constituents(10000, 0, 1200, 0, 0, 400));
            return map;
        });

        registerModMappings("irons_spellbooks", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("irons_spellbooks:arcane_essence", new Constituents(0, 0, 0, 0, 24, 6));
            map.put("irons_spellbooks:cinder_essence", new Constituents(0, 12, 0, 0, 12, 6));
            map.put("irons_spellbooks:hogskin", new Constituents(Elemenix.ORGANIX, 48));
            map.put("irons_spellbooks:common_ink", new Constituents(0, 25, 10, 0, 0, 4));
            map.put("irons_spellbooks:uncommon_ink", new Constituents(0, 25, 10, 0, 0, 8));
            map.put("irons_spellbooks:rare_ink", new Constituents(0, 25, 10, 0, 0, 16));
            map.put("irons_spellbooks:epic_ink", new Constituents(0, 25, 10, 0, 0, 32));
            map.put("irons_spellbooks:legendary_ink", new Constituents(0, 25, 10, 0, 0, 64));
            map.put("irons_spellbooks:blank_rune", new Constituents(0, 480, 0, 0, 0, 200));
            map.put("irons_spellbooks:mithril_scrap", new Constituents(0, 0, 0, 864, 0, 40));
            map.put("irons_spellbooks:raw_mithril", new Constituents(0, 24, 0, 864, 0, 40));
            map.put("#c:ores/mithril", new Constituents(0, 48, 0, 864, 0, 40));
            map.put("irons_spellbooks:pyrium_ingot", new Constituents(0, 40000, 0, 60000, 0, 4500));
            map.put("irons_spellbooks:lightning_bottle", new Constituents(0, 8, 0, 0, 128, 24));
            map.put("irons_spellbooks:frozen_bone", new Constituents(6, 24, 8, 0, 0, 0));
            map.put("irons_spellbooks:blood_vial", new Constituents(16, 8, 24, 0, 0, 2));
            map.put("irons_spellbooks:icy_fang", new Constituents(12, 20, 12, 0, 0, 2));
            map.put("irons_spellbooks:ice_venom_vial", new Constituents(12, 28, 16, 0, 0, 2));
            map.put("irons_spellbooks:bloody_vellum", new Constituents(80, 0, 0, 0, 0, 8));
            map.put("irons_spellbooks:dragonskin", new Constituents(1000, 0, 0, 0, 500, 500));
            map.put("irons_spellbooks:ruined_book", new Constituents(92, 0, 0, 0, 160, 100));
            map.put("irons_spellbooks:timeless_slurry", new Constituents(0, 18, 12, 0, 120, 32));
            map.put("irons_spellbooks:divine_soulshard", new Constituents(0, 32, 1200, 0, 0, 1000));
            map.put("irons_spellbooks:ancient_knowledge_fragment", new Constituents(6, 2, 0, 0, 0, 2));
            map.put("irons_spellbooks:permafrost_shard", new Constituents(0, 0, 120, 0, 0, 200));
            map.put("irons_spellbooks:decrepit_key", new Constituents(0, 0, 0, 640, 200, 1000));
            map.put("irons_spellbooks:fire_ale", new Constituents(12, 8, 24, 0, 42, 40));
            map.put("irons_spellbooks:netherward_tincture", new Constituents(24, 8, 12, 0, 0, 20));
            map.put("irons_spellbooks:disc_fragment_flame_still_burns", new Constituents(0, 64, 0, 0, 5, 30));
            map.put("irons_spellbooks:music_disc_dead_king_lullaby", new Constituents(0, 550, 0, 0, 20, 300));
            map.put("irons_spellbooks:ice_spider_egg", new Constituents(50, 16, 45, 0, 0, 0));
            map.put("irons_spellbooks:lightning_rod", new Constituents(0, 352, 0, 864, 1024, 192));
            map.put("irons_spellbooks:blood_staff", new Constituents(120, 21500, 120, 0, 320, 1000));
            map.put("irons_spellbooks:magehunter", new Constituents(12, 0, 0, 14280, 0, 400));
            map.put("irons_spellbooks:keeper_flamberge", new Constituents(0, 15600, 0, 25600, 11500, 2200));
            map.put("irons_spellbooks:decrepit_scythe", new Constituents(0, 15620, 0, 25800, 12000, 2250));
            map.put("irons_spellbooks:autoloader_crossbow", new Constituents(102, 13, 0, 756, 0, 0));
            map.put("irons_spellbooks:hither_thither_wand", new Constituents(120, 12000, 8000, 0, 0, 1500));
            map.put("irons_spellbooks:silver_ring", new Constituents(0, 0, 0, 1728, 0, 120));
            map.put("irons_spellbooks:teleportation_amulet", new Constituents(0, 53, 0, 792, 0, 260));
            map.put("irons_spellbooks:betrayer_signet", new Constituents(0, 0, 0, 1728, 0, 250));
            map.put("irons_spellbooks:invisibility_ring", new Constituents(0, 0, 120, 1728, 0, 200));
            map.put("irons_spellbooks:villager_spell_book", new Constituents(92, 800, 0, 320, 160, 800));
            map.put("irons_spellbooks:rotten_spell_book", new Constituents(492, 0, 0, 0, 160, 400));
            map.put("irons_spellbooks:blaze_spell_book", new Constituents(92, 0, 0, 0, 448, 400));
            map.put("irons_spellbooks:necronomicon_spell_book", new Constituents(182, 0, 0, 320, 540, 600));
            map.put("irons_spellbooks:evoker_spell_book", new Constituents(92, 0, 24, 1728, 320, 900));
            map.put("irons_spellbooks:chained_book", new Constituents(92, 11, 0, 264, 0, 0));
            return map;
        });

        registerModMappings("anvilcraft", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("anvilcraft:magnet_ingot", new Constituents(0, 9, 0, 216, 18, 0));
            map.put("anvilcraft:sapphire", new Constituents(Elemenix.TERRIX, 800));
            map.put("anvilcraft:topaz", new Constituents(Elemenix.TERRIX, 800));
            map.put("anvilcraft:ruby", new Constituents(Elemenix.TERRIX, 800));
            map.put("anvilcraft:wood_fiber", new Constituents(Elemenix.ORGANIX, 64));
            map.put("anvilcraft:resin", new Constituents(Elemenix.ORGANIX, 32));
            map.put("anvilcraft:amber", new Constituents(Elemenix.ORGANIX, 32));
            map.put("anvilcraft:hardend_resin", new Constituents(Elemenix.ORGANIX, 32));
            map.put("anvilcraft:geode", new Constituents(Elemenix.TERRIX, 2400));
            map.put("anvilcraft:royal_steel_ingot", new Constituents(0, 21114, 0, 648, 0, 405));
            map.put("anvilcraft:brass_ingot", new Constituents(0, 18, 0, 117, 0, 0));
            map.put("anvilcraft:bronze_ingot", new Constituents(0, 18, 0, 117, 0, 0));
            map.put("anvilcraft:cursed_gold_ingot", new Constituents(0, 0, 0, 432, 0, 72));
            map.put("anvilcraft:frost_metal_ingot", new Constituents(0, 30, 32, 675, 0, 0));
            map.put("anvilcraft:ember_metal_ingot", new Constituents(0, 72000, 0, 119340, 18000, 9000));
            map.put("anvilcraft:lime_powder", new Constituents(Elemenix.TERRIX, 8));
            map.put("anvilcraft:flour", new Constituents(Elemenix.ORGANIX, 12));
            map.put("anvilcraft:quartz_sand", new Constituents(Elemenix.TERRIX, 32));
            map.put("anvilcraft:nether_dust", new Constituents(0, 19, 0, 0, 1, 0));
            map.put("anvilcraft:end_dust", new Constituents(Elemenix.TERRIX, 40));
            map.put("anvilcraft:levitation_powder", new Constituents(Elemenix.TERRIX, 20));
            map.put("anvilcraft:cinerite", new Constituents(Elemenix.TERRIX, 28));
            map.put("anvilcraft:earth_core_shard_ore", new Constituents(0, 131694, 0, 0, 18000, 9000));
            map.put("anvilcraft:earth_core_shard", new Constituents(0, 131670, 0, 0, 18000, 9000));
            map.put("anvilcraft:crab_claw", new Constituents(240, 0, 100, 0, 0, 0));
            map.put("anvilcraft:multiphase_matter", new Constituents(0, 67, 1800, 1518, 1800, 400));
            map.put("anvilcraft:royal_steel_upgrade_smithing_template", new Constituents(0, 0, 0, 16480, 0, 450));
            map.put("anvilcraft:frost_metal_upgrade_smithing_template", new Constituents(0, 0, 1200, 16480, 0, 450));
            map.put("anvilcraft:ember_metal_upgrade_smithing_template", new Constituents(0, 72000, 0, 135820, 18000, 9450));
            map.put("anvilcraft:spectral_anvil", new Constituents(0, 0, 3448, 0, 0, 48));
            map.put("anvilcraft:discharger", new Constituents(0, 326, 0, 2952, 144, 0));
            map.put("anvilcraft:acceleration_ring", new Constituents(0, 9656, 0, 173628, 576, 0));
            map.put("anvilcraft:deflection_ring", new Constituents(0, 7832, 0, 160128, 1440, 0));
            map.put("anvilcraft:tempering_glass", new Constituents(0, 2671, 0, 81, 0, 50));
            map.put("anvilcraft:ember_glass", new Constituents(0, 9032, 0, 14917, 2250, 1125));
            map.put("anvilcraft:cream", new Constituents(6, 0, 2, 0, 0, 0));
            map.put("anvilcraft:cocoa_powder", new Constituents(12, 0, 0, 0, 0, 0));
            map.put("anvilcraft:nesting_shulker_box", new Constituents(384, 512, 0, 0, 0, 80));
            map.put("anvilcraft:over_nesting_shulker_box", new Constituents(576, 768, 0, 0, 0, 120));
            map.put("anvilcraft:supercritical_nesting_shulker_box", new Constituents(768, 1027, 0, 0, 0, 160));
            map.put("anvilcraft:tin_can", new Constituents(0, 18, 0, 432, 0, 0));
            map.put("anvilcraft:dough", new Constituents(0, 12, 0, 4, 0, 0));
            map.put("anvilcraft:cocoa_butter", new Constituents(6, 0, 6, 0, 0, 0));
            map.put("anvilcraft:beef_mushroom_stew", new Constituents(94, 0, 24, 0, 0, 0));
            map.put("anvilcraft:utusan", new Constituents(122, 3, 39, 0, 0, 11));
            map.put("anvilcraft:sea_heart_shell_shard", new Constituents(0, 0, 2500, 0, 30, 25));
            map.put("anvilcraft:sea_heart_shell", new Constituents(0, 0, 5000, 0, 60, 50));
            map.put("anvilcraft:prismarine_cluster", new Constituents(0, 0, 2500, 0, 30, 25));
            map.put("anvilcraft:prismarine_blade", new Constituents(0, 0, 1200, 0, 0, 340));
            map.put("anvilcraft:corrupted_beacon", new Constituents(0, 912, 32, 0, 20000, 4500));
            map.put("anvilcraft:giant_anvil", new Constituents(0, 4186, 0, 100602, 0, 0));
            map.put("anvilcraft:power_converter_middle", new Constituents(0, 138, 0, 888, 48, 0));
            map.put("anvilcraft:cake_base_block", new Constituents(Elemenix.ORGANIX, 38));
            map.put("anvilcraft:cream_block", new Constituents(44, 0, 8, 0, 0, 0));
            map.put("anvilcraft:berry_cream_block", new Constituents(52, 0, 14, 0, 0, 0));
            map.put("anvilcraft:chocolate_cream_block", new Constituents(70, 0, 15, 0, 0, 0));
            map.put("anvilcraft:cake_block", new Constituents(82, 0, 8, 0, 0, 0));
            map.put("anvilcraft:berry_cake_block", new Constituents(90, 0, 14, 0, 0, 0));
            map.put("anvilcraft:chocolate_cake_block", new Constituents(108, 0, 15, 0, 0, 0));
            map.put("anvilcraft:chocolate", new Constituents(Elemenix.ORGANIX, 26));
            map.put("anvilcraft:chocolate_white", new Constituents(Elemenix.ORGANIX, 17));
            map.put("anvilcraft:chocolate_black", new Constituents(Elemenix.ORGANIX, 30));
            map.put("anvilcraft:large_cake", new Constituents(1656, 0, 157, 0, 0, 0));
            map.put("anvilcraft:neutronium_ingot", new Constituents(0, 320_000_004, 0, 0, 0, 2_000_007));
            map.put("anvilcraft:charged_neutronium_ingot", new Constituents(0, 320_000_004, 0, 0, 40000, 2_000_007));
            map.put("anvilcraft:sponge_gemmule", new Constituents(33, 0, 30, 0, 0, 0));
            map.put("anvilcraft:oil_bucket", new Constituents(1600, 27, 0, 648, 800, 0));
            return map;
        });

        registerModMappings("ars_nouveau", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("ars_nouveau:wilden_horn", new Constituents(32, 24, 0, 0, 0, 12));
            map.put("ars_nouveau:wilden_wing", new Constituents(32, 12, 0, 0, 0, 15));
            map.put("ars_nouveau:wilden_spike", new Constituents(90, 0, 0, 0, 0, 5));
            map.put("ars_nouveau:sourceberry_bush", new Constituents(10, 0, 6, 0, 0, 1));
            map.put("ars_nouveau:bombegranate_pod", new Constituents(24, 0, 6, 0, 16, 0));
            map.put("ars_nouveau:mendosteen_pod", new Constituents(40, 0, 6, 0, 0, 0));
            map.put("ars_nouveau:frostaya_pod", new Constituents(24, 0, 22, 0, 0, 0));
            map.put("ars_nouveau:bastion_pod", new Constituents(24, 16, 6, 0, 0, 0));
            map.put("ars_nouveau:magebloom", new Constituents(20, 0, 8, 0, 0, 4));
            map.put("ars_nouveau:magebloom_seeds", new Constituents(5, 0, 0, 0, 0, 1));
            map.put("ars_nouveau:source_gem", new Constituents(0, 18, 0, 0, 0, 20));
            map.put("ars_nouveau:abjuration_essence", new Constituents(0, 24, 0, 0, 0, 10));
            map.put("ars_nouveau:conjuration_essence", new Constituents(Elemenix.ARCANIX, 34));
            map.put("ars_nouveau:air_essence", new Constituents(0, 0, 24, 0, 0, 10));
            map.put("ars_nouveau:water_essence", new Constituents(0, 0, 24, 0, 0, 10));
            map.put("ars_nouveau:earth_essence", new Constituents(24, 0, 0, 0, 0, 10));
            map.put("ars_nouveau:fire_essence", new Constituents(0, 0, 0, 0, 24, 10));
            map.put("ars_nouveau:manipulation_essence", new Constituents(Elemenix.ARCANIX, 34));
            map.put("ars_nouveau:sourcestone", new Constituents(0, 26, 0, 0, 0, 2));
            map.put("ars_nouveau:sourcestone_sconce", new Constituents(0, 70, 0, 0, 0, 24));
            map.put("ars_nouveau:magebloom_fiber", new Constituents(5, 0, 2, 0, 0, 1));
            map.put("ars_nouveau:music_disc_aria_biblio", new Constituents(0, 550, 0, 0, 0, 300));
            map.put("ars_nouveau:music_disc_firel_the_wild_hunt", new Constituents(0, 550, 0, 0, 0, 300));
            map.put("ars_nouveau:music_disc_thistle_the_sound_of_glass", new Constituents(0, 550, 0, 0, 0, 300));
            map.put("ars_nouveau:basic_spell_turret", new Constituents(0, 234, 0, 1728, 54, 80));
            map.put("ars_nouveau:arcane_pedestal", new Constituents(0, 122, 0, 192, 0, 28));
            map.put("ars_nouveau:whirlisprig_shards", new Constituents(120, 0, 0, 0, 0, 24));
            map.put("ars_nouveau:drygmy_shard", new Constituents(60, 60, 0, 0, 0, 24));
            map.put("ars_nouveau:starbuncle_shards", new Constituents(0, 0, 0, 120, 0, 24));
            map.put("ars_nouveau:wixie_shards", new Constituents(0, 8, 20, 0, 0, 56));
            map.put("ars_nouveau:alakarkinos_token", new Constituents(0, 120, 0, 0, 0, 24));
            map.put("ars_nouveau:wilden_tribute", new Constituents(0, 2400, 0, 0, 0, 500));
            map.put("ars_nouveau:experience_gem", new Constituents(0, 12, 0, 0, 0, 8));
            map.put("ars_nouveau:rune", new Constituents(0, 5, 0, 0, 0, 2));
            map.put("ars_nouveau:bookwyrm_charm", new Constituents(560, 240, 0, 0, 0, 125));
            map.put("ars_nouveau:amethyst_golem_charm", new Constituents(560, 0, 0, 0, 0, 100));
            map.put("ars_nouveau:pierce_arrow", new Constituents(4, 12, 0, 0, 0, 4));
            map.put("ars_nouveau:split_arrow", new Constituents(4, 12, 0, 0, 0, 4));
            map.put("ars_nouveau:amplify_arrow", new Constituents(4, 12, 0, 0, 0, 4));
            return map;
        });

        registerModMappings("arsdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("arsdelight:wilden_meat", Constituents.rawMeat(10));
            map.put("arsdelight:chimera_meat", Constituents.rawMeat(18));
            map.put("arsdelight:source_berry_pie_slice", new Constituents(26, 0, 8, 0, 0, 0));
            map.put("arsdelight:chimera_horn", new Constituents(10, 80, 0, 0, 0, 100));
            return map;
        });

        registerModMappings("natures_spirit", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("natures_spirit:desert_turnip", new Constituents(26, 0, 8, 0, 0, 0));
            map.put("natures_spirit:desert_turnip_root_block", new Constituents(35, 0, 16, 0, 0, 0));
            map.put("natures_spirit:shiitake_mushroom", new Constituents(18, 0, 6, 0, 0, 0));
            map.put("natures_spirit:shiitake_mushroom_block", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("natures_spirit:gray_polypore", new Constituents(18, 0, 6, 0, 0, 0));
            map.put("natures_spirit:gray_polypore_block", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("natures_spirit:olives", new Constituents(20, 0, 9, 0, 0, 0));
            map.put("natures_spirit:olive_branch", new Constituents(36, 0, 8, 0, 0, 0));
            map.put("natures_spirit:chalk_powder", new Constituents(Elemenix.TERRIX, 6));
            map.put("natures_spirit:calcite_shard", new Constituents(Elemenix.TERRIX, 8));
            map.put("natures_spirit:calcite_cluster", new Constituents(Elemenix.TERRIX, 32));
            map.put("natures_spirit:large_calcite_bud", new Constituents(Elemenix.TERRIX, 24));
            map.put("natures_spirit:small_calcite_bud", new Constituents(Elemenix.TERRIX, 12));
            map.put("natures_spirit:red_moss_block", new Constituents(6, 0, 6, 0, 0, 0));
            map.put("natures_spirit:coconut", new Constituents(24, 0, 32, 0, 0, 0));
            map.put("natures_spirit:coconut_shell", new Constituents(Elemenix.ORGANIX, 18));
            map.put("natures_spirit:coconut_sprout", new Constituents(32, 0, 24, 0, 0, 0));
            map.put("natures_spirit:frosty_redwood_leaves", new Constituents(6, 0, 4, 0, 0, 0));
            map.put("natures_spirit:frosty_fir_leaves", new Constituents(6, 0, 4, 0, 0, 0));
            map.put("natures_spirit:azolla", Constituents.seagrass());
            map.put("natures_spirit:lotus_stem", Constituents.seagrass());
            map.put("natures_spirit:helvola_pad", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("natures_spirit:framed_paper_block", new Constituents(Elemenix.ORGANIX, 152));
            map.put("#natures_spirit:small_grass", Constituents.grassVineLeaves());
            map.put("#natures_spirit:large_grass", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("#natures_spirit:vines", Constituents.grassVineLeaves());
            map.put("#natures_spirit:plants_double_dye", Constituents.flowerLarge());
            map.put("#natures_spirit:plants_single_dye", Constituents.flower());
            map.put("#natures_spirit:plants_quadruple_dye", new Constituents(72, 0, 32, 0, 0, 0));
            map.put("natures_spirit:alluaudia", new Constituents(32, 0, 16, 0, 0, 0));
            map.put("natures_spirit:stripped_alluaudia", new Constituents(32, 0, 16, 0, 0, 0));
            return map;
        });

        registerModMappings("vanillabackport", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("vanillabackport:pale_moss_block", new Constituents(6, 0, 6, 0, 0, 0));
            map.put("vanillabackport:pale_hanging_moss", new Constituents(6, 0, 3, 0, 0, 0));
            map.put("vanillabackport:closed_eyeblossom", new Constituents(18, 0, 8, 0, 0, 2));
            map.put("vanillabackport:open_eyeblossom", new Constituents(18, 0, 8, 0, 0, 2));
            map.put("vanillabackport:resin_clump", new Constituents(Elemenix.ORGANIX, 8));
            return map;
        });

        registerModMappings("delighto_flight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("delighto_flight:cloud", new Constituents(Elemenix.FLUMIX, 32));
            map.put("delighto_flight:phantom_wing", new Constituents(41, 24, 0, 0, 0, 8));
            map.put("delighto_flight:copper_thunder_fruit", new Constituents(16, 0, 0, 24, 24, 0));
            map.put("delighto_flight:cloud_berries", new Constituents(8, 0, 6, 0, 0, 0));
            map.put("delighto_flight:thunder_fruit_seeds", new Constituents(4, 0, 0, 0, 2, 0));
            map.put("delighto_flight:thunder_fruit", new Constituents(32, 0, 8, 0, 16, 0));
            map.put("delighto_flight:clear_cloudshroom", new Constituents(18, 0, 6, 0, 0, 0));
            map.put("delighto_flight:rainy_cloudshroom", new Constituents(18, 0, 12, 0, 0, 0));
            map.put("delighto_flight:thunder_cloudshroom", new Constituents(18, 0, 12, 0, 6, 0));
            map.put("delighto_flight:cloudshroom_colony", new Constituents(90, 0, 30, 0, 0, 0));
            map.put("delighto_flight:magic_chef_hat", new Constituents(240, 0, 0, 0, 0, 40));
            map.put("delighto_flight:cook_book", new Constituents(92, 0, 0, 0, 0, 20));
            map.put("delighto_flight:weather_soil_farmland", new Constituents(86, 34, 32, 0, 0, 40));
            map.put("delighto_flight:cloud_berry_pancake", new Constituents(21, 4, 9, 0, 0, 0));
            map.put("delighto_flight:thunder_fruit_stew", new Constituents(41, 0, 5, 0, 4, 0));
            map.put("delighto_flight:mushroom_hotpot", new Constituents(130, 15, 7, 0, 13, 0));
            map.put("delighto_flight:sparktricity_soda", new Constituents(38, 8, 48, 0, 6, 0));
            return map;
        });

        registerModMappings("cobblemon", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("#cobblemon:herbs", new Constituents(32, 0, 12, 0, 0, 5));
            map.put("#cobblemon:apricorns", new Constituents(24, 0, 8, 0, 0, 0));
            map.put("#cobblemon:apricorn_sprouts", new Constituents(64, 0, 24, 0, 0, 0));
            map.put("#cobblemon:mint_seeds", new Constituents(6, 0, 0, 0, 0, 1));
            map.put("#cobblemon:mint_leaves", new Constituents(16, 0, 6, 0, 0, 5));
            map.put("#cobblemon:tumblestones", new Constituents(Elemenix.TERRIX, 20));
            map.put("#cobblemon:tumblestone_small_buds", new Constituents(Elemenix.TERRIX, 20));
            map.put("#cobblemon:tumblestone_medium_buds", new Constituents(Elemenix.TERRIX, 40));
            map.put("#cobblemon:tumblestone_large_buds", new Constituents(Elemenix.TERRIX, 60));
            map.put("#cobblemon:tumblestone_clusters", new Constituents(Elemenix.TERRIX, 80));
            map.put("#cobblemon:evolution_stones_arcanix", new Constituents(0, 240, 0, 0, 0, 53));
            map.put("#cobblemon:evolution_stones_energix", new Constituents(0, 240, 0, 0, 48, 5));
            map.put("#cobblemon:evolution_stones_flumix", new Constituents(0, 240, 48, 0, 0, 5));
            map.put("#cobblemon:evolution_stones_organix", new Constituents(48, 240, 0, 0, 0, 5));
            map.put("#cobblemon:evolution_stone_ores_arcanix", new Constituents(0, 264, 0, 0, 0, 53));
            map.put("#cobblemon:evolution_stone_ores_energix", new Constituents(0, 264, 0, 0, 48, 5));
            map.put("#cobblemon:evolution_stone_ores_flumix", new Constituents(0, 264, 48, 0, 0, 5));
            map.put("#cobblemon:evolution_stone_ores_organix", new Constituents(48, 264, 0, 0, 0, 5));
            map.put("#cobblemon:type_gems_arcanix", new Constituents(0, 240, 0, 0, 0, 104));
            map.put("#cobblemon:type_gems_energix", new Constituents(0, 240, 0, 0, 80, 24));
            map.put("#cobblemon:type_gems_flumix", new Constituents(0, 240, 80, 0, 0, 24));
            map.put("#cobblemon:type_gems_metallix", new Constituents(0, 240, 0, 80, 0, 24));
            map.put("#cobblemon:type_gems_organix", new Constituents(80, 240, 0, 0, 0, 24));
            map.put("#cobblemon:type_gems_terrix", new Constituents(0, 320, 0, 0, 0, 24));
            map.put("#cobblemon:berries", new Constituents(30, 0, 12, 0, 0, 5));
            map.put("#cobblemon:berries/mutation_result", new Constituents(35, 0, 16, 0, 0, 8));
            map.put("#cobblemon:fossils", new Constituents(1000, 20000, 0, 0, 0, 420));
            map.put("cobblemon:old_amber_fossil", new Constituents(21000, 0, 0, 0, 0, 420));
            map.put("cobblemon:sitrus_berry", new Constituents(45, 0, 20, 0, 0, 8));
            map.put("cobblemon:roseli_berry", new Constituents(32, 0, 20, 0, 0, 12));
            map.put("cobblemon:lum_berry", new Constituents(35, 0, 20, 0, 0, 8));
            map.put("cobblemon:medicinal_leek", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("cobblemon:big_root", new Constituents(30, 0, 10, 0, 5, 0));
            map.put("cobblemon:energy_root", new Constituents(24, 0, 10, 0, 0, 0));
            map.put("cobblemon:revival_herb", new Constituents(30, 0, 15, 0, 5, 0));
            map.put("cobblemon:pep_up_flower", Constituents.flower());
            map.put("cobblemon:vivichoke", new Constituents(32, 0, 18, 0, 5, 0));
            map.put("cobblemon:vivichoke_seeds", new Constituents(Elemenix.ORGANIX, 15));
            map.put("cobblemon:galarica_nuts", new Constituents(8, 0, 6, 0, 0, 0));
            map.put("cobblemon:hearty_grains", new Constituents(24, 0, 3, 0, 0, 0));
            map.put("cobblemon:tasty_tail", new Constituents(40, 0, 20, 0, 0, 0));
            map.put("cobblemon:automaton_armor_trim_smithing_template", new Constituents(0, 140000, 0, 0, 0, 2800));
            map.put("cobblemon:pokerod_smithing_template", new Constituents(0, 12, 0, 3024, 0, 0));
            map.put("cobblemon:relic_coin_pouch", new Constituents(Elemenix.METALLIX, 432));
            map.put("cobblemon:tart_apple", new Constituents(32, 0, 15, 0, 0, 0));
            map.put("cobblemon:sweet_apple", new Constituents(32, 0, 15, 0, 0, 0));
            map.put("cobblemon:syrupy_apple", new Constituents(40, 0, 15, 0, 0, 0));
            map.put("cobblemon:absorb_bulb", new Constituents(80, 0, 35, 0, 0, 0));
            map.put("cobblemon:black_sludge", new Constituents(15, 32, 10, 0, 0, 0));
            map.put("cobblemon:everstone", new Constituents(0, 250, 0, 0, 0, 100));
            map.put("cobblemon:deep_sea_scale", new Constituents(80, 0, 0, 0, 0, 32));
            map.put("cobblemon:deep_sea_tooth", new Constituents(10, 70, 0, 0, 0, 32));
            map.put("cobblemon:razor_fang", new Constituents(25, 150, 0, 0, 0, 20));
            map.put("cobblemon:razor_claw", new Constituents(175, 0, 0, 0, 0, 20));
            map.put("cobblemon:grip_claw", new Constituents(50, 0, 0, 15, 0, 10));
            map.put("cobblemon:lagging_tail", new Constituents(Elemenix.TERRIX, 320));
            map.put("cobblemon:leftovers", new Constituents(16, 0, 6, 0, 0, 32));
            map.put("cobblemon:float_stone", new Constituents(0, 80, 20, 0, 0, 12));
            map.put("cobblemon:light_ball", new Constituents(0, 12, 0, 0, 140, 50));
            map.put("cobblemon:lucky_egg", new Constituents(120, 90, 0, 0, 0, 50));
            map.put("cobblemon:metal_powder", new Constituents(12, 0, 0, 320, 0, 0));
            map.put("cobblemon:quick_claw", new Constituents(150, 0, 0, 0, 0, 50));
            map.put("cobblemon:quick_powder", new Constituents(162, 0, 0, 0, 0, 50));
            map.put("cobblemon:sharp_beak", new Constituents(90, 0, 0, 0, 0, 10));
            map.put("cobblemon:shed_shell", new Constituents(15, 80, 0, 0, 0, 10));
            map.put("cobblemon:sticky_barb", new Constituents(0, 20, 0, 350, 0, 0));
            map.put("cobblemon:electric_seed", new Constituents(80, 0, 0, 0, 80, 15));
            map.put("cobblemon:grassy_seed", new Constituents(160, 0, 0, 0, 0, 15));
            map.put("cobblemon:misty_seed", new Constituents(80, 0, 80, 0, 0, 15));
            map.put("cobblemon:psychic_seed", new Constituents(80, 0, 0, 0, 0, 95));
            map.put("cobblemon:smoke_ball", new Constituents(0, 24, 12, 0, 0, 0));
            map.put("cobblemon:moomoo_milk", new Constituents(10, 8, 12, 0, 0, 0));
            map.put("cobblemon:exp_candy_s", new Constituents(360, 0, 0, 0, 12, 24));
            map.put("cobblemon:exp_candy_l", new Constituents(324, 0, 0, 0, 108, 216));
            map.put("cobblemon:ability_capsule", new Constituents(1200, 0, 0, 0, 0, 120));
            map.put("cobblemon:ability_patch", new Constituents(9800, 0, 0, 0, 200, 800));
            map.put("cobblemon:dragon_scale", new Constituents(120, 0, 0, 0, 0, 32));
            map.put("cobblemon:prism_scale", new Constituents(80, 0, 0, 0, 0, 20));
            map.put("cobblemon:black_augurite", new Constituents(0, 125, 0, 0, 0, 24));
            map.put("cobblemon:chipped_pot", new Constituents(0, 18, 0, 1344, 0, 0));
            map.put("cobblemon:masterpiece_teacup", new Constituents(0, 34, 0, 0, 0, 0));
            map.put("cobblemon:auspicious_armor", new Constituents(0, 0, 0, 1728, 120, 35));
            map.put("cobblemon:malicious_armor", new Constituents(0, 0, 120, 1728, 0, 35));
            map.put("cobblemon:shell_helmet", new Constituents(24, 320, 0, 0, 0, 32));
            map.put("cobblemon:metal_alloy", new Constituents(0, 0, 0, 1200, 0, 15));
            map.put("cobblemon:scroll_of_darkness", new Constituents(1320, 0, 0, 0, 0, 100));
            map.put("cobblemon:scroll_of_waters", new Constituents(1200, 0, 120, 0, 0, 100));
            map.put("cobblemon:oval_stone", new Constituents(0, 200, 0, 0, 12, 24));
            map.put("cobblemon:rare_candy", new Constituents(1944, 0, 0, 0, 648, 648));
            return map;
        });

        registerModMappings("youkaishomecoming", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("#c:tea_leaves", new Constituents(10, 0, 4, 0, 0, 0));
            map.put("youkaishomecoming:pods", new Constituents(20, 0, 8, 0, 0, 0));
            map.put("youkaishomecoming:soybean", new Constituents(Elemenix.ORGANIX, 20));
            map.put("youkaishomecoming:redbean", new Constituents(Elemenix.ORGANIX, 20));
            map.put("youkaishomecoming:green_coffee_bean", new Constituents(Elemenix.ORGANIX, 15));
            map.put("youkaishomecoming:tea_seeds", new Constituents(Elemenix.ORGANIX, 4));
            map.put("youkaishomecoming:coffee_beans", new Constituents(Elemenix.ORGANIX, 15));
            map.put("youkaishomecoming:coffee_berries", new Constituents(15, 0, 6, 0, 0, 0));
            map.put("youkaishomecoming:raw_lamprey", new Constituents(40, 2, 20, 0, 0, 0));
            map.put("youkaishomecoming:lamprey_bucket", new Constituents(40, 29, 20, 648, 0, 0));
            map.put("youkaishomecoming:roe", new Constituents(12, 0, 8, 0, 0, 0));
            map.put("youkaishomecoming:butter", new Constituents(Elemenix.ORGANIX, 24));
            map.put("youkaishomecoming:udumbara_flower", new Constituents(28, 0, 12, 0, 0, 8));
            map.put("youkaishomecoming:udumbara_seeds", new Constituents(Elemenix.ORGANIX, 4));
            map.put("youkaishomecoming:soy_sauce_bottle", new Constituents(14, 8, 6, 0, 0, 0));
            map.put("youkaishomecoming:suigei", new Constituents(49, 0, 11, 0, 0, 1));
            map.put("youkaishomecoming:full_moons_eve", new Constituents(46, 0, 7, 0, 0, 2));
            map.put("youkaishomecoming:sparrow_sake", new Constituents(46, 0, 7, 0, 0, 2));
            map.put("youkaishomecoming:kappa_village", new Constituents(42, 0, 7, 0, 0, 0));
            map.put("youkaishomecoming:hakutsuru", new Constituents(42, 0, 8, 0, 0, 0));
            map.put("youkaishomecoming:mio", new Constituents(24, 8, 5, 0, 0, 0));
            map.put("youkaishomecoming:mead", new Constituents(39, 0, 13, 0, 0, 0));
            map.put("youkaishomecoming:tengu_tango", new Constituents(48, 0, 5, 0, 0, 2));
            map.put("youkaishomecoming:kiku", new Constituents(40, 0, 5, 0, 0, 0));
            return map;
        });
    }

    public static void registerModMappings(String modId, Supplier<Map<String, Constituents>> mappingSupplier) {
        MOD_ELEMENIX_MAPPINGS.put(modId, mappingSupplier);
    }

    public static Map<String, Constituents> getModMappings(String modId) {
        Supplier<Map<String, Constituents>> supplier = MOD_ELEMENIX_MAPPINGS.get(modId);
        return supplier != null ? supplier.get() : Collections.emptyMap();
    }

    public static Set<String> getAvailableModMappings() {
        return MOD_ELEMENIX_MAPPINGS.keySet();
    }
}
