package net.lghast.elemenix.utils;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.function.Supplier;

public class ModElemenixMapping {
    private static final Map<String, Supplier<Map<String, Constituents>>> MOD_ELEMENIX_MAPPINGS = new HashMap<>();

    static {
        registerModMappings("farmersdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("farmersdelight:straw", new Constituents(Elemenix.ORGANIX, 24));
            map.put("farmersdelight:tomato", new Constituents(20, 0, 12, 0, 0, 0));
            map.put("farmersdelight:rotten_tomato", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("farmersdelight:onion", new Constituents(20, 0, 10, 0, 0, 0));
            map.put("farmersdelight:cabbage", new Constituents(26, 0, 8, 0, 0, 0));
            map.put("farmersdelight:rice_panicle", new Constituents(24, 0, 5, 0, 0, 0));
            map.put("farmersdelight:rice", new Constituents(24, 0, 0, 0, 0, 0));
            map.put("farmersdelight:tree_bark", new Constituents(Elemenix.ORGANIX, 7));
            map.put("farmersdelight:rope", new Constituents(12, 0, 0, 0, 0, 0));
            map.put("farmersdelight:sandy_shrub", Constituents.grassVineLeaves());
            map.put("farmersdelight:canvas", new Constituents(Elemenix.ORGANIX, 96));
            map.put("farmersdelight:tatami", new Constituents(Elemenix.ORGANIX, 120));
            map.put("farmersdelight:full_tatami_mat", new Constituents(Elemenix.ORGANIX, 60));
            map.put("#farmersdelight:wild_crops", new Constituents(64, 0, 24, 0, 0, 0));
            map.put("farmersdelight:brown_mushroom_colony", new Constituents(90, 0, 30, 0, 0, 0));
            map.put("farmersdelight:red_mushroom_colony", new Constituents(90, 0, 30, 0, 0, 0));
            map.put("farmersdelight:wheat_dough", new Constituents(24, 0, 4, 0, 0, 0));
            map.put("farmersdelight:chicken_cuts", new Constituents(15, 0, 4, 0, 0, 0));
            map.put("farmersdelight:cod_slice", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("farmersdelight:salmon_slice", new Constituents(15, 0, 4, 0, 0, 0));
            map.put("farmersdelight:ham", new Constituents(86, 24, 16, 0, 0, 0));
            map.put("farmersdelight:smoked_ham", new Constituents(86, 24, 3, 0, 10, 0));
            map.put("farmersdelight:cake_slice", new Constituents(17, 0, 1, 0, 0, 0));
            map.put("farmersdelight:apple_pie_slice", new Constituents(70, 0, 11, 0, 0, 0));
            map.put("farmersdelight:chocolate_pie_slice", new Constituents(42, 0, 5, 0, 0, 0));
            map.put("farmersdelight:sweet_berry_cheesecake_slice", new Constituents(30, 0, 9, 0, 0, 0));
            map.put("farmersdelight:roast_chicken", new Constituents(72, 0, 10, 0, 7, 0));
            map.put("farmersdelight:shepherds_pie", new Constituents(51, 0, 5, 0, 12, 0));
            map.put("farmersdelight:stuffed_pumpkin", new Constituents(64, 0, 27, 0, 0, 0));
            map.put("farmersdelight:honey_glazed_ham", new Constituents(74, 0, 6, 0, 2, 0));
            map.put("farmersdelight:rich_soil", new Constituents(86, 34, 0, 0, 0, 0));
            map.put("farmersdelight:rich_soil_farmland", new Constituents(86, 34, 0, 0, 0, 0));
            return map;
        });

        registerModMappings("twilightforest", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("twilightforest:chiseled_canopy_bookshelf", new Constituents(Elemenix.ORGANIX, 180));
            map.put("twilightforest:mangrove_root", new Constituents(Elemenix.ORGANIX, 18));
            map.put("twilightforest:root", new Constituents(Elemenix.ORGANIX, 18));
            map.put("twilightforest:moss_patch", new Constituents(3, 0, 2, 0, 0, 0));
            map.put("twilightforest:mining_log_core", new Constituents(96, 0, 0, 30, 0, 500));
            map.put("twilightforest:time_log_core", new Constituents(96, 0, 0, 30, 50, 450));
            map.put("twilightforest:transformation_log_core", new Constituents(96, 0, 0, 30, 50, 450));
            map.put("twilightforest:sorting_log_core", new Constituents(96, 0, 0, 30, 0, 500));
            map.put("twilightforest:mayapple", Constituents.grassVineLeaves());
            map.put("twilightforest:clover_patch", Constituents.grassVineLeaves());
            map.put("twilightforest:fiddlehead", Constituents.grassVineLeaves());
            map.put("twilightforest:mushgloom", new Constituents(18, 0, 6, 0, 2, 0));
            map.put("twilightforest:huge_mushgloom", new Constituents(36, 0, 12, 0, 4, 0));
            map.put("twilightforest:huge_mushgloom_stem", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("twilightforest:torchberries", new Constituents(8, 0, 4, 0, 2, 0));
            map.put("twilightforest:torchberry_plant", new Constituents(24, 0, 10, 0, 5, 0));
            map.put("twilightforest:fallen_leaves", new Constituents(4, 0, 2, 0, 0, 0));
            map.put("twilightforest:root_strand", new Constituents(Elemenix.ORGANIX, 12));
            map.put("twilightforest:hedge", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("twilightforest:firefly", new Constituents(18, 2, 5, 0, 3, 0));
            map.put("twilightforest:cicada", new Constituents(20, 0, 8, 0, 0, 0));
            map.put("twilightforest:moonworm", new Constituents(18, 0, 5, 0, 2, 0));
            map.put("twilightforest:moonworm_queen", new Constituents(180, 0, 60, 0, 50, 50));
            map.put("twilightforest:nagastone", Constituents.stone());
            map.put("twilightforest:etched_nagastone", Constituents.stone());
            map.put("twilightforest:nagastone_head", Constituents.stone());
            map.put("twilightforest:nagastone_pillar", Constituents.stone());
            map.put("twilightforest:nagastone_stairs_left", Constituents.stone());
            map.put("twilightforest:nagastone_stairs_right", Constituents.stone());
            map.put("twilightforest:cracked_nagastone_stairs_left", Constituents.stone());
            map.put("twilightforest:cracked_nagastone_stairs_right", Constituents.stone());
            map.put("twilightforest:mossy_nagastone_stairs_left", new Constituents(6, 24, 0, 0, 0, 0));
            map.put("twilightforest:mossy_nagastone_stairs_right", new Constituents(6, 24, 0, 0, 0, 0));
            map.put("twilightforest:mazestone", new Constituents(Elemenix.TERRIX, 40));
            map.put("twilightforest:wrought_iron_bar", new Constituents(0, 3, 0, 80, 0, 0));
            map.put("twilightforest:huge_water_lily", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("twilightforest:huge_lily_pad", new Constituents(72, 0, 40, 0, 0, 0));
            map.put("twilightforest:underbrick", Constituents.stone());
            map.put("twilightforest:smoker", new Constituents(80, 0, 10, 0, 30, 30));
            map.put("twilightforest:fire_jet", new Constituents(80, 0, 0, 0, 80, 50));
            map.put("twilightforest:aurora_block", new Constituents(Elemenix.ENERGIX, 24));
            map.put("twilightforest:uberous_soil", new Constituents(86, 34, 0, 0, 0, 16));
            map.put("twilightforest:deadrock", new Constituents(Elemenix.TERRIX, 200));
            map.put("twilightforest:cracked_deadrock", new Constituents(Elemenix.TERRIX, 180));
            map.put("twilightforest:weathered_deadrock", new Constituents(Elemenix.TERRIX, 160));
            map.put("twilightforest:giant_cobblestone", new Constituents(Elemenix.TERRIX, 1536));
            map.put("twilightforest:giant_log", new Constituents(Elemenix.ORGANIX, 6144));
            map.put("twilightforest:giant_leaves", new Constituents(384, 0, 128, 0, 0, 0));
            map.put("twilightforest:giant_obsidian", new Constituents(Elemenix.TERRIX, 7680));
            map.put("twilightforest:trollsteinn", Constituents.stone());
            map.put("twilightforest:castle_brick", Constituents.stone());
            map.put("twilightforest:huge_stalk", new Constituents(96, 0, 30, 0, 0, 0));
            map.put("twilightforest:trollvidr", new Constituents(Elemenix.ORGANIX, 12));
            map.put("twilightforest:unripe_trollber", new Constituents(16, 0, 4, 0, 0, 0));
            map.put("twilightforest:trollber", new Constituents(32, 0, 26, 0, 12, 0));
            map.put("twilightforest:raven_feather", new Constituents(24, 0, 0, 0, 0, 2));
            map.put("twilightforest:maze_map_focus", new Constituents(24, 0, 0, 0, 0, 80));
            map.put("twilightforest:charm_of_life_1", new Constituents(20, 0, 0, 120, 0, 50));
            map.put("twilightforest:charm_of_keeping_1", new Constituents(120, 0, 0, 20, 0, 50));
            map.put("twilightforest:transformation_powder", new Constituents(48, 0, 0, 0, 5, 30));
            map.put("twilightforest:raw_venison", Constituents.rawMeat(8));
            map.put("twilightforest:raw_meef", Constituents.rawMeat(6, 2));
            map.put("twilightforest:maze_wafer", new Constituents(Elemenix.ORGANIX, 50));
            map.put("twilightforest:steeleaf_ingot", new Constituents(100, 0, 0, 540, 0, 200));
            map.put("twilightforest:liveroot", new Constituents(36, 0, 0, 0, 0, 200));
            map.put("twilightforest:liveroot_block", new Constituents(45, 0, 0, 0, 0, 200));
            map.put("twilightforest:ironwood_ingot", new Constituents(18, 0, 0, 136, 0, 100));
            map.put("twilightforest:borer_essence", new Constituents(20, 20, 0, 0, 12, 1));
            map.put("twilightforest:naga_scale", new Constituents(1200, 120, 0, 0, 0, 400));
            map.put("twilightforest:trophy_pedestal", new Constituents(0, 5000, 0, 50, 0, 150));
            map.put("twilightforest:ghast_trap", new Constituents(464, 0, 0, 360, 400, 800));
            map.put("twilightforest:antibuilder", new Constituents(1200, 0, 0, 10000, 900, 5000));
            map.put("twilightforest:locked_vanishing_block", new Constituents(60, 2, 0, 0, 1, 0));
            map.put("twilightforest:tower_key", new Constituents(0, 0, 0, 720, 0, 500));
            map.put("twilightforest:red_thread", new Constituents(42, 0, 0, 0, 5, 0));
            map.put("twilightforest:arctic_fur", new Constituents(36, 0, 4, 0, 0, 0));
            map.put("twilightforest:alpha_yeti_fur", new Constituents(1350, 0, 30, 0, 0, 350));
            map.put("twilightforest:armor_shard", new Constituents(0, 0, 0, 62, 0, 25));
            map.put("twilightforest:knightmetal_block", new Constituents(0, 0, 0, 5022, 0, 2025));
            map.put("twilightforest:diamond_minotaur_axe", new Constituents(24, 62000, 0, 0, 0, 1300));
            map.put("twilightforest:golden_minotaur_axe", new Constituents(24, 0, 0, 1555, 0, 100));
            map.put("twilightforest:fiery_tears", new Constituents(60, 0, 500, 0, 3400, 450));
            map.put("twilightforest:fiery_blood", new Constituents(60, 0, 500, 0, 3400, 450));
            map.put("twilightforest:magic_beans", new Constituents(12288, 0, 0, 0, 0, 100));
            map.put("twilightforest:crown_splinter", new Constituents(0, 0, 0, 5000, 0, 150));
            map.put("twilightforest:exanimate_essence", new Constituents(0, 200, 0, 0, 2000, 100));
            map.put("twilightforest:fluffy_cloud", new Constituents(Elemenix.FLUMIX, 4));
            map.put("twilightforest:wispy_cloud", new Constituents(Elemenix.FLUMIX, 4));
            map.put("twilightforest:rainy_cloud", new Constituents(Elemenix.FLUMIX, 32));
            map.put("twilightforest:snowy_cloud", new Constituents(Elemenix.FLUMIX, 32));
            map.put("twilightforest:greater_potion_flask", new Constituents(Elemenix.TERRIX, 32));
            map.put("twilightforest:brittle_potion_flask", new Constituents(Elemenix.TERRIX, 32));
            map.put("twilightforest:coronation_carpet", new Constituents(Elemenix.ORGANIX, 80));
            map.put("twilightforest:ore_magnet", new Constituents(0, 0, 0, 432, 0, 100));
            map.put("twilightforest:ice_bomb", new Constituents(0, 10, 36, 0, 0, 0));
            map.put("twilightforest:ice_sword", new Constituents(24, 0, 700, 124, 0, 0));
            map.put("twilightforest:ice_bow", new Constituents(72, 0, 700, 124, 0, 0));
            map.put("twilightforest:glass_sword", new Constituents(24, 2400, 0, 0, 0, 10));
            map.put("twilightforest:phantom_helmet", new Constituents(0, 0, 0, 50000, 0, 2400));
            map.put("twilightforest:phantom_chestplate", new Constituents(0, 0, 0, 80000, 0, 3500));
            map.put("twilightforest:triple_bow", new Constituents(72, 0, 0, 2592, 0, 500));
            map.put("twilightforest:ender_bow", new Constituents(72, 0, 0, 2592, 0, 900));
            map.put("twilightforest:seeker_bow", new Constituents(72, 0, 0, 2592, 0, 750));
            map.put("twilightforest:lamp_of_cinders", new Constituents(0, 0, 0, 2916, 0, 2000));
            map.put("twilightforest:emperors_cloth", new Constituents(160, 0, 80, 0, 0, 300));
            map.put("twilightforest:ore_meter", new Constituents(160, 0, 0, 1500, 0, 1200));
            map.put("twilightforest:pocket_watch", new Constituents(0, 24, 0, 1200, 24, 1200));
            map.put("twilightforest:moon_dial", new Constituents(18, 24, 0, 2400, 24, 400));
            map.put("twilightforest:crumble_horn", new Constituents(2400, 0, 0, 0, 0, 2000));
            map.put("twilightforest:peacock_fan", new Constituents(1200, 0, 300, 0, 0, 1000));
            map.put("twilightforest:twilight_scepter", new Constituents(60, 240, 0, 0, 3000, 2000));
            map.put("twilightforest:zombie_scepter", new Constituents(3060, 240, 0, 0, 0, 2000));
            map.put("twilightforest:lifedrain_scepter", new Constituents(60, 240, 3000, 0, 0, 2000));
            map.put("twilightforest:fortification_scepter", new Constituents(60, 240, 0, 3000, 0, 2000));
            map.put("twilightforest:carminite", new Constituents(104, 152, 0, 0, 72, 204));
            map.put("twilightforest:fiery_ingot", new Constituents(60, 0, 500, 216, 3400, 450));
            map.put("twilightforest:hydra_chop", new Constituents(405, 0, 50, 0, 50, 30));
            map.put("twilightforest:experiment_115", new Constituents(115, 115, 115, 115, 115, 115));
            map.put("twilightforest:meef_stroganoff", new Constituents(178, 0, 46, 0, 2, 200));
            map.put("twilightforest:stronghold_shield", new Constituents(0, 60000, 0, 3200, 0, 800));
            map.put("twilightforest:mazebreaker_pickaxe", new Constituents(24, 200, 0, 35000, 0, 5000));
            map.put("twilightforest:skull_chest", new Constituents(0, 600, 0, 0, 0, 10));
            map.put("twilightforest:keepsake_casket", new Constituents(0, 600, 0, 320, 0, 50));
            map.put("twilightforest:chipped_keepsake_casket", new Constituents(0, 480, 0, 256, 0, 40));
            map.put("twilightforest:damaged_keepsake_casket", new Constituents(0, 300, 0, 160, 0, 25));
            return map;
        });

        registerModMappings("mynethersdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("mynethersdelight:powder_cannon", new Constituents(6, 0, 0, 0, 1, 0));
            map.put("mynethersdelight:stripped_powdery_block", new Constituents(54, 0, 0, 0, 9, 0));
            map.put("mynethersdelight:bullet_pepper", new Constituents(24, 0, 0, 0, 12, 0));
            map.put("mynethersdelight:pepper_powder", new Constituents(2, 0, 0, 0, 12, 0));
            map.put("mynethersdelight:hoglin_loin", Constituents.rawMeat(7));
            map.put("mynethersdelight:hoglin_sausage", new Constituents(17, 0, 4, 0, 0, 0));
            map.put("mynethersdelight:ghasta", new Constituents(24, 0, 0, 0, 2, 2));
            map.put("mynethersdelight:ghasmati", new Constituents(22, 0, 0, 0, 2, 2));
            map.put("mynethersdelight:hoglin_hide", new Constituents(Elemenix.ORGANIX, 160));
            map.put("mynethersdelight:strider_slice", new Constituents(36, 0, 6, 0, 2, 0));
            map.put("mynethersdelight:minced_strider", new Constituents(6, 0, 3, 0, 1, 0));
            map.put("mynethersdelight:strider_rock", new Constituents(30, 24, 8, 0, 5, 0));
            map.put("mynethersdelight:strider_egg", new Constituents(30, 5, 8, 0, 3, 0));
            map.put("mynethersdelight:enchanted_golden_egg", new Constituents(30, 0, 8, 10015, 1000, 1000));
            map.put("mynethersdelight:crimson_fungus_colony", new Constituents(225, 0, 85, 0, 0, 0));
            map.put("mynethersdelight:warped_fungus_colony", new Constituents(225, 0, 85, 0, 0, 0));
            map.put("mynethersdelight:resurgent_soil", new Constituents(80, 50, 14, 0, 8, 0));
            map.put("mynethersdelight:resurgent_soil_farmland", new Constituents(80, 50, 14, 0, 8, 0));
            map.put("mynethersdelight:cold_striderloaf", new Constituents(72, 0, 15, 0, 0, 0));
            map.put("mynethersdelight:plate_of_striderloaf", new Constituents(25, 0, 3, 0, 1, 0));
            map.put("mynethersdelight:plate_of_cold_striderloaf", new Constituents(25, 0, 3, 0, 0, 0));
            map.put("mynethersdelight:hot_cream_cone", new Constituents(9, 57, 1, 0, 29, 0));
            map.put("mynethersdelight:hot_wings_bucket", new Constituents(111, 27, 42, 648, 36, 0));
            map.put("mynethersdelight:slices_of_bread", new Constituents(Elemenix.ORGANIX, 20));
            map.put("mynethersdelight:roast_ear", new Constituents(23, 1, 8, 0, 0, 0));
            map.put("mynethersdelight:plate_of_stuffed_hoglin_snout", new Constituents(182, 4, 43, 0, 1, 0));
            map.put("mynethersdelight:plate_of_stuffed_hoglin_ham", new Constituents(158, 3, 39, 0, 1, 0));
            map.put("mynethersdelight:plate_of_stuffed_hoglin", new Constituents(158, 3, 39, 0, 1, 0));
            map.put("mynethersdelight:magma_cake_slice", new Constituents(12, 25, 0, 0, 28, 1));
            map.put("mynethersdelight:hoglin_trophy", new Constituents(286, 120, 0, 432, 0, 0));
            map.put("mynethersdelight:skoglin_trophy", new Constituents(126, 120, 0, 432, 0, 0));
            map.put("mynethersdelight:golden_trophy", new Constituents(126, 120, 0, 6912, 0, 0));
            return map;
        });

        registerModMappings("twilightdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("twilightdelight:mushgloom_colony", new Constituents(90, 0, 30, 0, 10, 0));
            map.put("twilightdelight:experiment_110", new Constituents(110, 110, 110, 110, 110, 110));
            map.put("twilightdelight:experiment_113", new Constituents(113, 113, 113, 113, 113, 113));
            map.put("twilightdelight:raw_tomahawk_smeak", new Constituents(60, 0, 20, 0, 0, 0));
            map.put("twilightdelight:aurora_pie_slice", new Constituents(46, 0, 0, 0, 18, 0));
            map.put("twilightdelight:torchberry_pie_slice", new Constituents(52, 0, 3, 0, 1, 0));
            map.put("twilightdelight:plate_of_fiery_snakes", new Constituents(395, 30, 138, 0, 856, 216));
            map.put("twilightdelight:plate_of_lily_chicken", new Constituents(94, 0, 23, 0, 7, 0));
            map.put("twilightdelight:meef_wellington", new Constituents(70, 4, 11, 0, 1, 0));
            return map;
        });

        registerModMappings("endersdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("endersdelight:mite_crust", new Constituents(6, 0, 0, 0, 0, 1));
            map.put("endersdelight:enderman_sight", new Constituents(16, 0, 0, 0, 0, 12));
            map.put("endersdelight:shulker_mollusk", new Constituents(40, 0, 10, 0, 0, 10));
            map.put("endersdelight:stuffed_shulker_bowl", new Constituents(51, 32, 7, 0, 0, 9));
            map.put("endersdelight:ethereal_saffron", new Constituents(24, 0, 6, 0, 0, 5));
            map.put("endersdelight:amberveil", new Constituents(18, 0, 6, 0, 0, 3));
            map.put("endersdelight:chorusflame", new Constituents(18, 0, 8, 0, 2, 2));
            map.put("endersdelight:voidpepper", new Constituents(24, 0, 6, 0, 0, 3));
            return map;
        });

        registerModMappings("rusticdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("rusticdelight:cotton_boll", new Constituents(Elemenix.ORGANIX, 24));
            map.put("rusticdelight:bell_pepper_green", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("rusticdelight:bell_pepper_red", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("rusticdelight:bell_pepper_yellow", new Constituents(18, 0, 8, 0, 0, 0));
            map.put("rusticdelight:calamari", new Constituents(25, 0, 10, 0, 0, 0));
            map.put("rusticdelight:coffee_beans", new Constituents(Elemenix.ORGANIX, 20));
            map.put("rusticdelight:pancake", new Constituents(41, 0, 2, 0, 0, 0));
            map.put("rusticdelight:honey_pancake", new Constituents(40, 0, 2, 0, 0, 0));
            map.put("rusticdelight:chocolate_pancake", new Constituents(33, 0, 4, 0, 0, 0));
            map.put("rusticdelight:cherry_blossom_pancake", new Constituents(25, 0, 2, 0, 0, 0));
            map.put("rusticdelight:vegetable_pancake", new Constituents(29, 0, 3, 0, 0, 0));
            map.put("rusticdelight:pumpkin_pancake", new Constituents(39, 0, 13, 0, 0, 0));
            map.put("rusticdelight:syrup_cheesecake_slice", new Constituents(59, 0, 10, 0, 0, 0));
            map.put("rusticdelight:cherry_blossom_cheesecake_slice", new Constituents(33, 0, 2, 0, 0, 0));
            return map;
        });

        registerModMappings("jiagureappear", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("jiagureappear:sour_berries", new Constituents(8, 0, 6, 0, 0, 0));
            map.put("jiagureappear:shadow_berries", new Constituents(8, 0, 4, 0, 0, 2));
            map.put("jiagureappear:turtle_plastron", new Constituents(12, 0, 64, 0, 0, 0));
            map.put("jiagureappear:yolime", new Constituents(35, 0, 10, 0, 0, 10));
            map.put("jiagureappear:zucchini", new Constituents(72, 0, 68, 0, 0, 0));
            map.put("#jiagureappear:amethyst_inscriptions", new Constituents(true));
            return map;
        });

        registerModMappings("crittersandcompanions", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("crittersandcompanions:dragonfly_wing", new Constituents(Elemenix.ORGANIX, 16));
            map.put("crittersandcompanions:koi_fish", new Constituents(20, 2, 12, 0, 0, 0));
            map.put("crittersandcompanions:clam", new Constituents(15, 36, 5, 0, 0, 0));
            map.put("crittersandcompanions:pearl", new Constituents(Elemenix.TERRIX, 24));
            map.put("crittersandcompanions:silk", new Constituents(Elemenix.ORGANIX, 24));
            map.put("crittersandcompanions:silk_cocoon", new Constituents(Elemenix.ORGANIX, 72));
            map.put("crittersandcompanions:sea_bunny_slime_bottle", new Constituents(30, 8, 15, 0, 0, 0));
            map.put("crittersandcompanions:koi_fish_bucket", new Constituents(20, 29, 12, 648, 0, 0));
            map.put("crittersandcompanions:sea_bunny_bucket", new Constituents(30, 27, 15, 648, 0, 0));
            map.put("crittersandcompanions:dumbo_octopus_bucket", new Constituents(30, 27, 15, 648, 0, 0));
            return map;
        });

        registerModMappings("dungeonsdelight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("dungeonsdelight:wormroot_tendrils", new Constituents(Elemenix.ORGANIX, 12));
            map.put("dungeonsdelight:wormroot_stalk", new Constituents(Elemenix.ORGANIX, 48));
            map.put("dungeonsdelight:wormouth", new Constituents(Elemenix.ORGANIX, 144));
            map.put("dungeonsdelight:rotbulb", new Constituents(24, 0, 6, 0, 0, 0));
            map.put("dungeonsdelight:rotbulb_crop", new Constituents(24, 0, 6, 0, 0, 0));
            map.put("dungeonsdelight:rotbulb_plant", new Constituents(42, 0, 8, 0, 0, 0));
            map.put("dungeonsdelight:stained_scrap", new Constituents(18, 0, 0, 270, 0, 9));
            map.put("dungeonsdelight:heap_of_ancient_eggs", new Constituents(54, 40, 30, 0, 20, 20));
            map.put("dungeonsdelight:sniffer_shank", Constituents.rawMeat(8, 2));
            map.put("dungeonsdelight:gritty_flesh", new Constituents(18, 10, 2, 0, 0, 0));
            map.put("dungeonsdelight:brined_flesh", new Constituents(26, 0, 8, 0, 0, 0));
            map.put("dungeonsdelight:spider_meat", Constituents.rawMeat(5));
            map.put("dungeonsdelight:bogged_brain", new Constituents(26, 0, 12, 0, 0, 0));
            map.put("dungeonsdelight:silverfish_abdomen", new Constituents(12, 2, 2, 0, 0, 0));
            map.put("dungeonsdelight:ghast_tentacle", new Constituents(24, 0, 0, 0, 2, 2));
            map.put("dungeonsdelight:fried_ghast_calamari", new Constituents(12, 0, 0, 0, 3, 1));
            map.put("dungeonsdelight:ancient_egg", new Constituents(10, 8, 6, 0, 2, 2));
            map.put("dungeonsdelight:soft_serve_sniffer_egg", new Constituents(70, 16, 12, 0, 16, 0));
            map.put("dungeonsdelight:polterghast_pizza_slice", new Constituents(32, 0, 8, 0, 2, 2));
            map.put("dungeonsdelight:candied_silverfish_sucker", new Constituents(64, 300, 11, 0, 0, 0));
            map.put("dungeonsdelight:candied_vex_sucker", new Constituents(40, 300, 10, 0, 0, 10));
            map.put("dungeonsdelight:glow_berry_gelatin", new Constituents(34, 6, 4, 0, 18, 1));
            map.put("dungeonsdelight:ossobuco", new Constituents(36, 12, 6, 0, 0, 0));
            map.put("dungeonsdelight:guardian_angel", new Constituents(57, 6, 21, 96, 19, 1));
            map.put("dungeonsdelight:silverfish_and_chips", new Constituents(47, 6, 7, 0, 16, 1));
            map.put("dungeonsdelight:bug_chops", Constituents.rawMeat(8));
            map.put("dungeonsdelight:monster_cake_slice", new Constituents(45, 1, 11, 0, 0, 1));
            map.put("dungeonsdelight:spider_pie_slice", new Constituents(123, 0, 20, 0, 0, 1));
            map.put("dungeonsdelight:sculk_tart_slice", new Constituents(35, 6, 4, 0, 2, 2));
            return map;
        });

        registerModMappings("create", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("#c:ores/zinc", new Constituents(Elemenix.TERRIX, 102));
            map.put("#create:packages", new Constituents(Elemenix.ORGANIX, 24));
            map.put("create:raw_zinc", new Constituents(Elemenix.TERRIX, 78));
            map.put("create:zinc_ingot", new Constituents(0, 6, 0, 72, 0, 0));
            map.put("create:andesite_alloy", new Constituents(0, 28, 0, 8, 0, 0));
            map.put("create:andesite_casing", new Constituents(96, 28, 0, 8, 0, 0));
            map.put("create:brass_casing", new Constituents(96, 15, 0, 72, 0, 0));
            map.put("create:copper_casing", new Constituents(96, 24, 0, 72, 0, 0));
            map.put("create:powdered_obsidian", new Constituents(Elemenix.TERRIX, 30));
            map.put("create:sturdy_sheet", new Constituents(Elemenix.TERRIX, 150));
            map.put("create:railway_casing", new Constituents(96, 165, 0, 72, 0, 0));
            map.put("create:cinder_flour", new Constituents(10, 0, 0, 0, 1, 0));
            map.put("create:precision_mechanism", new Constituents(72, 15, 0, 460, 0, 0));
            map.put("create:stressometer", new Constituents(96, 82, 0, 872, 6, 0));
            map.put("create:wheat_flour", new Constituents(Elemenix.ORGANIX, 12));
            map.put("create:dough", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("create:blaze_burner", new Constituents(0, 55, 0, 864, 217, 0));
            map.put("create:blaze_cake", new Constituents(36, 38, 6, 0, 192, 0));
            map.put("create:brass_ingot", new Constituents(0, 9, 0, 72, 0, 0));
            map.put("create:attribute_filter", new Constituents(96, 2, 0, 16, 0, 0));
            map.put("create:experience_nugget", new Constituents(0, 0, 0, 0, 2, 2));
            map.put("create:track", new Constituents(0, 12, 0, 16, 0, 0));
            map.put("create:cardboard", new Constituents(Elemenix.ORGANIX, 24));
            map.put("create:haunted_bell", new Constituents(0, 90, 0, 720, 0, 5));
            map.put("create:bar_of_chocolate", new Constituents(39, 0, 5, 0, 0, 0));
            map.put("create:sweet_roll", new Constituents(Elemenix.ORGANIX, 73));
            map.put("create:chocolate_glazed_berries", new Constituents(47, 0, 11, 0, 0, 0));
            map.put("create:honeyed_apple", new Constituents(92, 0, 15, 0, 0, 0));
            map.put("create:builders_tea", new Constituents(3, 8, 6, 0, 2, 0));
            map.put("create:asurine", new Constituents(0, 20, 0, 4, 0, 0));
            map.put("create:crimsite", new Constituents(0, 20, 0, 4, 0, 0));
            map.put("create:limestone", Constituents.stone());
            map.put("create:ochrum", new Constituents(0, 20, 0, 4, 0, 0));
            map.put("create:veridium", new Constituents(0, 20, 0, 4, 0, 0));
            return map;
        });

        registerModMappings("eternal_starlight", () -> {
            Map<String, Constituents> map = new HashMap<>();
            map.put("#c:ores/atalphaite", new Constituents(0, 124, 0, 0, 96, 0));
            map.put("#c:ores/starlit_diamond", new Constituents(0, 41024, 0, 0, 0, 1200));
            map.put("#c:ores/swamp_silver", new Constituents(0, 24, 0, 3456, 0, 45));
            map.put("#c:ores/malarite", new Constituents(0, 8024, 0, 0, 0, 100));
            map.put("#c:ores/saltpeter", new Constituents(0, 120, 0, 0, 48, 0));
            map.put("eternal_starlight:saltpeter_powder", new Constituents(0, 96, 0, 0, 48, 0));
            map.put("eternal_starlight:swamp_silver_ingot", new Constituents(0, 0, 0, 3456, 0, 45));
            map.put("eternal_starlight:malarite", new Constituents(0, 8000, 0, 0, 0, 100));
            map.put("eternal_starlight:torreya_vines", new Constituents(6, 0, 2, 0, 4, 0));
            map.put("eternal_starlight:algaleaves", new Constituents(5, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:hanging_algaleaves", new Constituents(5, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:glowing_voidstone", new Constituents(0, 22, 0, 0, 5, 0));
            map.put("eternal_starlight:eternal_ice", new Constituents(Elemenix.FLUMIX, 60));
            map.put("eternal_starlight:eternal_ice_atalphaite_ore", new Constituents(0, 100, 60, 0, 96, 0));
            map.put("eternal_starlight:eternal_ice_starlit_diamond_ore", new Constituents(0, 41000, 60, 0, 96, 1200));
            map.put("eternal_starlight:eternal_ice_saltpeter_ore", new Constituents(0, 96, 60, 0, 48, 0));
            map.put("eternal_starlight:eternal_ice_redstone_ore", new Constituents(0, 18, 60, 0, 6, 0));
            map.put("eternal_starlight:icicle", new Constituents(Elemenix.FLUMIX, 24));
            map.put("eternal_starlight:haze_ice", new Constituents(0, 12, 48, 0, 0, 0));
            map.put("eternal_starlight:haze_ice_atalphaite_ore", new Constituents(0, 112, 48, 0, 96, 0));
            map.put("eternal_starlight:haze_ice_starlit_diamond_ore", new Constituents(0, 41012, 48, 0, 96, 1200));
            map.put("eternal_starlight:haze_ice_saltpeter_ore", new Constituents(0, 108, 48, 0, 48, 0));
            map.put("eternal_starlight:haze_ice_redstone_ore", new Constituents(0, 30, 48, 0, 6, 0));
            map.put("eternal_starlight:ashen_snow", new Constituents(0, 4, 12, 0, 0, 0));
            map.put("eternal_starlight:ashen_snowball", new Constituents(0, 2, 6, 0, 0, 0));
            map.put("eternal_starlight:aethersent_ingot", new Constituents(0, 0, 0, 252, 0, 225));
            map.put("eternal_starlight:aethersent_nugget", new Constituents(0, 0, 0, 28, 0, 25));
            map.put("eternal_starlight:raw_aethersent", new Constituents(0, 252, 0, 0, 0, 225));
            map.put("eternal_starlight:creteor_hide", new Constituents(40, 0, 0, 0, 12, 45));
            map.put("eternal_starlight:starlit_diamond", new Constituents(0, 41250, 0, 0, 0, 1200));
            map.put("eternal_starlight:atalphaite", new Constituents(0, 100, 0, 0, 96, 0));
            map.put("eternal_starlight:dusted_gravel", new Constituents(Elemenix.TERRIX, 24));
            map.put("eternal_starlight:dusted_shard", new Constituents(Elemenix.TERRIX, 24));
            map.put("eternal_starlight:stellagmite", Constituents.stone());
            map.put("eternal_starlight:molten_stellagmite", new Constituents(0, 20, 4, 0, 2, 0));
            map.put("eternal_starlight:abysslate", Constituents.stone());
            map.put("eternal_starlight:abyssal_magma_block", new Constituents(0, 48, 0, 0, 120, 16));
            map.put("eternal_starlight:abyssal_geyser", new Constituents(0, 48, 0, 0, 20, 0));
            map.put("eternal_starlight:springstone", Constituents.stone());
            map.put("eternal_starlight:thermabysslate", new Constituents(0, 24, 0, 0, 2, 0));
            map.put("eternal_starlight:thermabyssal_magma_block", new Constituents(0, 48, 0, 0, 122, 16));
            map.put("eternal_starlight:thermabyssal_geyser", new Constituents(0, 48, 0, 0, 22, 0));
            map.put("eternal_starlight:cryobysslate", Constituents.stone());
            map.put("eternal_starlight:cryobysslate_magma_block", new Constituents(0, 48, 0, 0, 110, 16));
            map.put("eternal_starlight:cryobysslate_geyser", new Constituents(0, 48, 0, 0, 18, 0));
            map.put("eternal_starlight:thermal_springstone", new Constituents(0, 64, 0, 0, 80, 200));
            map.put("eternal_starlight:mossy_dusted_gravel", new Constituents(6, 24, 0, 0, 0, 0));
            map.put("eternal_starlight:glowing_mossy_dusted_gravel", new Constituents(6, 24, 0, 0, 2, 0));
            map.put("eternal_starlight:tooth_of_hunger", new Constituents(5, 24, 0, 0, 0, 100));
            map.put("eternal_starlight:nightfall_mud", new Constituents(6, 18, 4, 0, 0, 0));
            map.put("eternal_starlight:glowing_nightfall_mud", new Constituents(6, 18, 4, 0, 2, 0));
            map.put("eternal_starlight:nightfall_dirt", new Constituents(6, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:nightfall_farmland", new Constituents(6, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:nightfall_dirt_path", new Constituents(6, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:nightfall_grass_block", new Constituents(10, 18, 2, 0, 0, 0));
            map.put("eternal_starlight:tenacious_nightfall_grass_block", new Constituents(12, 18, 4, 0, 0, 0));
            map.put("eternal_starlight:nightfall_podzol", new Constituents(12, 16, 2, 0, 0, 0));
            map.put("eternal_starlight:fantasy_grass_block", new Constituents(10, 18, 2, 0, 0, 0));
            map.put("eternal_starlight:nightfall_grass_carpet", new Constituents(4, 0, 4, 0, 0, 0));
            map.put("eternal_starlight:lunar_berries", new Constituents(8, 0, 4, 0, 2, 0));
            map.put("eternal_starlight:abyssal_fruit", new Constituents(8, 0, 6, 0, 2, 0));
            map.put("eternal_starlight:orbflora", new Constituents(18, 0, 10, 0, 10, 0));
            map.put("eternal_starlight:orbflora_light", new Constituents(24, 0, 12, 0, 40, 0));
            map.put("eternal_starlight:nightfan_bush", Constituents.flower());
            map.put("eternal_starlight:moonlight_bush", Constituents.flower());
            map.put("eternal_starlight:pink_rose_bush", Constituents.flowerLarge());
            map.put("eternal_starlight:gladespike", Constituents.flower());
            map.put("eternal_starlight:vividstalk", Constituents.flower());
            map.put("eternal_starlight:tall_gladespike", Constituents.flowerLarge());
            map.put("eternal_starlight:night_sprouts", Constituents.grassVineLeaves());
            map.put("eternal_starlight:glowing_night_sprouts", new Constituents(6, 0, 2, 0, 2, 0));
            map.put("eternal_starlight:small_night_sprouts", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:small_glowing_night_sprouts", new Constituents(3, 0, 1, 0, 1, 0));
            map.put("eternal_starlight:lunar_grass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:glowing_lunar_grass", new Constituents(6, 0, 2, 0, 2, 0));
            map.put("eternal_starlight:lunar_bush", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("eternal_starlight:glowing_lunar_bush", new Constituents(12, 0, 4, 0, 4, 0));
            map.put("eternal_starlight:crescent_grass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:glowing_crescent_grass", new Constituents(6, 0, 2, 0, 2, 0));
            map.put("eternal_starlight:tall_crescent_grass", new Constituents(12, 0, 4, 0, 0, 0));
            map.put("eternal_starlight:tall_glowing_crescent_grass", new Constituents(12, 0, 4, 0, 4, 0));
            map.put("eternal_starlight:parasol_grass", new Constituents(8, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:glowing_parasol_grass", new Constituents(8, 0, 3, 0, 2, 0));
            map.put("eternal_starlight:lunar_reed", new Constituents(12, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:glowing_mushroom", new Constituents(18, 0, 6, 0, 2, 0));
            map.put("eternal_starlight:glowing_mushroom_block", new Constituents(36, 0, 12, 0, 4, 0));
            map.put("eternal_starlight:glowing_mushroom_stem", new Constituents(36, 0, 12, 0, 4, 0));
            map.put("eternal_starlight:bouldershroom", new Constituents(18, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:bouldershroom_block", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:bouldershroom_stem", new Constituents(36, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:bouldershroom_roots", new Constituents(18, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:cave_moss", Constituents.grassVineLeaves());
            map.put("eternal_starlight:marimold", new Constituents(18, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:marimold_block", new Constituents(36, 0, 24, 0, 0, 0));
            map.put("eternal_starlight:marimold_stem", new Constituents(36, 0, 24, 0, 0, 0));
            map.put("eternal_starlight:fantabud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:green_fantabud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:fantafern", Constituents.grassVineLeaves());
            map.put("eternal_starlight:green_fantafern", Constituents.grassVineLeaves());
            map.put("eternal_starlight:fantagrass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:green_fantagrass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:hanging_fantagrass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:orange_scarlet_bud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:purple_scarlet_bud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:red_scarlet_bud", new Constituents(3, 0, 1, 0, 0, 0));
            map.put("eternal_starlight:scarlet_grass", Constituents.grassVineLeaves());
            map.put("eternal_starlight:mauve_fern", Constituents.grassVineLeaves());
            map.put("eternal_starlight:amaramber_grass", new Constituents(18, 0, 8, 0, 1, 0));
            map.put("eternal_starlight:amaramber_bush", new Constituents(18, 0, 4, 0, 2, 0));
            map.put("eternal_starlight:red_starlight_crystal_shard", new Constituents(0, 300, 0, 0, 0, 60));
            map.put("eternal_starlight:blue_starlight_crystal_shard", new Constituents(0, 300, 0, 0, 0, 60));
            map.put("eternal_starlight:red_starlight_crystal_cluster", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:blue_starlight_crystal_cluster", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:red_starlight_crystal_block", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:blue_starlight_crystal_block", new Constituents(0, 1200, 0, 0, 0, 240));
            map.put("eternal_starlight:blooming_red_starlight_crystal_cluster", new Constituents(18, 1200, 8, 0, 0, 240));
            map.put("eternal_starlight:blooming_starlight_crystal_cluster", new Constituents(18, 1200, 8, 0, 0, 240));
            map.put("eternal_starlight:dead_lunar_bush", new Constituents(Elemenix.ORGANIX, 12));
            map.put("eternal_starlight:sunset_thornbloom", new Constituents(0, 18, 0, 0, 32, 0));
            map.put("eternal_starlight:amethysia_grass", new Constituents(8, 0, 3, 0, 0, 0));
            map.put("eternal_starlight:lunaris_cactus", new Constituents(18, 0, 10, 0, 0, 10));
            map.put("eternal_starlight:lunaris_cactus_fruit", new Constituents(18, 0, 10, 0, 0, 10));
            map.put("eternal_starlight:carved_lunaris_cactus_fruit", new Constituents(16, 0, 8, 0, 0, 10));
            map.put("eternal_starlight:lunaris_cactus_gel", new Constituents(18, 0, 2, 0, 0, 10));
            map.put("eternal_starlight:red_crystalfleur_vine", Constituents.grassVineLeaves());
            map.put("eternal_starlight:blue_crystalfleur_vine", Constituents.grassVineLeaves());
            map.put("eternal_starlight:red_crystal_moss_block", new Constituents(6, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:blue_crystal_moss_block", new Constituents(6, 0, 6, 0, 0, 0));
            map.put("eternal_starlight:moonlight_lily_pad", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("eternal_starlight:starlit_lily_pad", new Constituents(18, 0, 10, 0, 0, 0));
            map.put("eternal_starlight:moonlight_duckweed", new Constituents(6, 0, 8, 0, 0, 0));
            map.put("eternal_starlight:spiral_kelp", Constituents.seagrass());
            map.put("eternal_starlight:sea_rosa", Constituents.seagrass());
            map.put("eternal_starlight:wick_grass", Constituents.seagrass());
            map.put("eternal_starlight:lumenstem", new Constituents(18, 0, 8, 0, 3, 0));
            map.put("eternal_starlight:glacite", new Constituents(0, 12, 120, 0, 0, 200));
            map.put("eternal_starlight:glacite_shard", new Constituents(0, 0, 120, 0, 0, 200));
            map.put("eternal_starlight:rookfish", Constituents.rawMeat(7));
            map.put("eternal_starlight:rookfish_air_sac", new Constituents(24, 0, 8, 0, 0, 0));
            map.put("eternal_starlight:luminofish", Constituents.rawFish(6));
            map.put("eternal_starlight:luminaris", Constituents.rawFish(6));
            map.put("eternal_starlight:white_yeti_fur", new Constituents(Elemenix.ORGANIX, 96));
            map.put("eternal_starlight:raw_amaramber", new Constituents(360, 0, 0, 0, 10, 20));
            map.put("eternal_starlight:amaramber_ingot", new Constituents(180, 12, 0, 0, 5, 10));
            map.put("eternal_starlight:keeper_armor_trim_smithing_template", new Constituents(0, 24, 0, 24192, 0, 315));
            map.put("eternal_starlight:forge_armor_trim_smithing_template", new Constituents(0, 24, 0, 24192, 0, 315));
            map.put("eternal_starlight:blooming_armor_trim_smithing_template", new Constituents(84, 24, 0, 0, 35, 50));
            map.put("eternal_starlight:twining_armor_trim_smithing_template", new Constituents(84, 24, 0, 0, 35, 50));
            map.put("eternal_starlight:aurora_deer_steak", Constituents.rawMeat(8));
            map.put("eternal_starlight:ratlin_meat", Constituents.rawMeat(6));
            map.put("eternal_starlight:shadow_snail_meat", Constituents.rawMeat(5, 4));
            map.put("eternal_starlight:aurora_deer_antler", new Constituents(1200, 0, 0, 0, 0, 500));
            map.put("eternal_starlight:shadow_snail_shell", new Constituents(0, 72, 16, 0, 0, 0));
            map.put("eternal_starlight:frozen_tube", new Constituents(0, 8, 64, 12, 0, 0));
            map.put("eternal_starlight:shivering_gel", new Constituents(18, 0, 10, 0, 0, 16));
            map.put("eternal_starlight:nightfall_spider_eye", new Constituents(32, 8, 8, 0, 0, 5));
            map.put("eternal_starlight:gleech_egg", new Constituents(32, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:tangled_skull", new Constituents(50, 360, 0, 0, 0, 400));
            map.put("eternal_starlight:crystallized_sand", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:circulush", Constituents.seagrass());
            map.put("eternal_starlight:stonett", Constituents.seagrass());
            map.put("eternal_starlight:luminis", Constituents.seagrass());
            map.put("eternal_starlight:glowlis", Constituents.seagrass());
            map.put("eternal_starlight:glowreed", Constituents.seagrass());
            map.put("eternal_starlight:starlight_seagrass", Constituents.seagrass());
            map.put("eternal_starlight:jingling_pickle", new Constituents(18, 0, 12, 0, 5, 0));
            map.put("eternal_starlight:dead_tentacles_coral_block", new Constituents(36, 16, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_golden_coral_block", new Constituents(36, 16, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_crystallum_coral_block", new Constituents(36, 16, 0, 0, 0, 0));
            map.put("eternal_starlight:tentacles_coral_block", new Constituents(36, 16, 16, 0, 0, 0));
            map.put("eternal_starlight:golden_coral_block", new Constituents(36, 16, 16, 0, 0, 0));
            map.put("eternal_starlight:crystallum_coral_block", new Constituents(36, 16, 16, 0, 0, 0));
            map.put("eternal_starlight:dead_tentacles_coral", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_golden_coral", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_crystallum_coral", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:tentacles_coral", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:golden_coral", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:crystallum_coral", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:dead_tentacles_coral_fan", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_golden_coral_fan", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:dead_crystallum_coral_fan", new Constituents(18, 8, 0, 0, 0, 0));
            map.put("eternal_starlight:tentacles_coral_fan", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:golden_coral_fan", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:crystallum_coral_fan", new Constituents(18, 8, 8, 0, 0, 0));
            map.put("eternal_starlight:velvetumoss", new Constituents(140, 0, 40, 0, 0, 0));
            map.put("eternal_starlight:velvetumoss_ball", new Constituents(18, 0, 5, 0, 0, 0));
            map.put("eternal_starlight:velvetumoss_villi", new Constituents(7, 0, 2, 0, 0, 0));
            map.put("eternal_starlight:red_velvetumoss", new Constituents(70, 0, 20, 0, 0, 0));
            map.put("eternal_starlight:red_velvetumoss_villi", new Constituents(7, 0, 2, 0, 0, 0));
            map.put("eternal_starlight:red_velvetumoss_flower", new Constituents(24, 0, 12, 0, 0, 16));
            map.put("eternal_starlight:crystallized_lunar_grass", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:red_crystal_roots", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:blue_crystal_roots", new Constituents(Elemenix.TERRIX, 8));
            map.put("eternal_starlight:twilvewyrm_herb", Constituents.flowerLarge());
            map.put("eternal_starlight:stellafly_bush", Constituents.flowerLarge());
            map.put("eternal_starlight:glimmerflt_bush", new Constituents(36, 0, 16, 0, 10, 0));
            map.put("eternal_starlight:pungency_fruit_seeds", new Constituents(Elemenix.ORGANIX, 5));
            map.put("eternal_starlight:pungency_fruit", new Constituents(22, 0, 10, 0, 0, 0));
            map.put("eternal_starlight:seeds_launcher", new Constituents(1200, 0, 648, 0, 0, 150));
            map.put("eternal_starlight:rotten_flesh_jerky", new Constituents(18, 0, 2, 0, 0, 0));
            map.put("eternal_starlight:starfire_bird_nest", new Constituents(240, 18, 0, 0, 0, 0));
            map.put("eternal_starlight:starfire", new Constituents(0, 0, 0, 0, 500, 200));
            map.put("eternal_starlight:drying_rack", new Constituents(Elemenix.ORGANIX, 128));
            map.put("eternal_starlight:raw_flowglaze", new Constituents(0, 8, 0, 0, 500, 200));
            map.put("eternal_starlight:pungency_fruit_upgrade_smithing_template", new Constituents(0, 1348, 0, 0, 1424, 1400));
            map.put("eternal_starlight:starfire_upgrade_smithing_template", new Constituents(14, 56018, 10, 8, 2, 800));
            map.put("eternal_starlight:flowglaze_upgrade_smithing_template", new Constituents(0, 0, 900, 0, 0, 1400));
            map.put("eternal_starlight:ether_bucket", new Constituents(0, 27, 20, 648, 20, 0));
            map.put("eternal_starlight:thioquartz_shard", new Constituents(Elemenix.TERRIX, 24));
            map.put("eternal_starlight:thioquartz_cluster", new Constituents(Elemenix.TERRIX, 96));
            map.put("eternal_starlight:toxite", new Constituents(4, 20, 0, 0, 0, 0));
            map.put("eternal_starlight:rookfish_bucket", new Constituents(35, 27, 8, 648, 0, 0));
            map.put("eternal_starlight:luminofish_bucket", new Constituents(30, 29, 8, 648, 0, 0));
            map.put("eternal_starlight:luminaris_bucket", new Constituents(30, 29, 8, 648, 0, 0));
            map.put("eternal_starlight:starlight_silver_coin", new Constituents(0, 0, 0, 300, 0, 2));
            map.put("eternal_starlight:golem_steel_ingot", new Constituents(0, 99, 0, 12501, 0, 99));
            map.put("eternal_starlight:oxidized_golem_steel_ingot", new Constituents(0, 10098, 0, 2502, 0, 99));
            map.put("eternal_starlight:tenacious_petal", new Constituents(11520, 0, 120, 0, 0, 412));
            map.put("eternal_starlight:tenacious_vine", new Constituents(11520, 0, 80, 0, 0, 388));
            map.put("eternal_starlight:trapped_soul", new Constituents(0, 120, 1200, 0, 0, 100));
            map.put("eternal_starlight:shadegrieve", new Constituents(24, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:blooming_shadegrieve", new Constituents(24, 0, 12, 0, 0, 0));
            map.put("eternal_starlight:lunar_vine", Constituents.grassVineLeaves());
            map.put("eternal_starlight:shattered_sword", new Constituents(0, 12, 0, 6912, 0, 500));
            map.put("eternal_starlight:shattered_sword_blade", new Constituents(0, 0, 0, 6912, 0, 500));
            map.put("eternal_starlight:golem_steel_jet", new Constituents(0, 782, 0, 100008, 0, 792));
            map.put("eternal_starlight:oxidized_golem_steel_jet", new Constituents(0, 80784, 0, 20216, 0, 792));
            map.put("eternal_starlight:battleaxe_pendant", new Constituents(144, 0, 0, 648, 0, 600));
            map.put("eternal_starlight:warhammer_pendant", new Constituents(144, 0, 0, 648, 0, 600));
            map.put("eternal_starlight:crescent_pendant", new Constituents(144, 1296, 0, 0, 0, 600));
            map.put("eternal_starlight:butterfly_wings_amulet", new Constituents(144, 120, 1056, 120, 0, 600));
            map.put("eternal_starlight:fungus_amulet", new Constituents(1440, 0, 0, 0, 0, 600));
            map.put("eternal_starlight:pearl_necklace", new Constituents(144, 1296, 0, 0, 0, 600));
            return map;
        });
    }

    public static void registerModMappings(String modId, Supplier<Map<String, Constituents>> mappingSupplier) {
        MOD_ELEMENIX_MAPPINGS.put(modId, mappingSupplier);
    }

    public static Map<String, Constituents> getModMappings(String modId) {
        Supplier<Map<String, Constituents>> supplier = MOD_ELEMENIX_MAPPINGS.get(modId);
        return supplier != null ? supplier.get() : Collections.emptyMap();
    }

    public static Set<String> getAvailableModMappings() {
        return MOD_ELEMENIX_MAPPINGS.keySet();
    }
}
